### ISSUE TITLE
braceleft and braceright producing [  and ]  instead of {  and } 

### ISSUE THREAD

**Issue by davidkitfriedman** [openstenoproject/plover#1043]
## Summary

I'm using the latest Plover weekly-v4.0.0.dev8+66.g685bd33 as of July 2, 2018 on GNU/Linux Debian with OpenBox and {#braceleft}  and {#braceright} are producing [  and  ]  instead of {  and }.

[key_combo.py](https://github.com/openstenoproject/plover/blob/master/plover/key_combo.py#L34)

## Reproducing

One can make a dictionary entry and then test it out:

<pre>
"KPWR*BGT": "{#braceright}",
"KPWR-BGT": "{#braceleft}",
</pre>

## Plover Version

Plover 4.0.0.dev8+66.g685bd33

## System

- GNU/Linux Kernel 4.9.0-8
- Debian Stretch 9.6.0
- OpenBox 3.6.1-4
- AppImage

**Comment by morinted** [comment]
Hi David,

This is intended behavior that came up when considering support for many keyboard layouts.

We don't handle key modifiers at the key-name level. This is documented here: https://github.com/openstenoproject/plover/wiki/Dictionary-Format#keyboard-shortcuts

> `{#equal plus}` will send "==". Plover doesn't send modifiers. It just hits the key based on the name.

You'll want to use `{#shift(braceright)}` or `{#shift(bracketright)})`.

The reason we did this was to avoid accidentally pressing extra modifiers which can be very destructive actions. And if you wrote shift(a_shifted_key an_unshifted_thing), that's undefined behavior.

Finally, be sure that if you're writing the symbols, use a translation like `{^\{^}` instead of the keyboard shortcut syntax. The keyboard shortcut syntax is mainly useful for when you don't want the output to affect your buffer, as they aren't undoable with the asterisk key.

**Comment by davidkitfriedman** [comment]
Okay, thanks for clarifying that. 

David

**Comment by davidkitfriedman** [comment]
> Finally, be sure that if you're writing the symbols, use a translation like {^\\{^} instead of the keyboard shortcut syntax. The keyboard shortcut syntax is mainly useful for when you don't want the output to affect your buffer, as they aren't undoable with the asterisk key.

I think you must have meant there actually 
<pre>
{^\\{^}
</pre> 

instead of 

<pre>
{^\{^}
</pre>. 

This looks like an issue with the markup, and so it also showed up in my email with just one backslash instead of two.
