### ISSUE TITLE
ProCat Blaze is connected but won't work with Plover for some reason

### ISSUE THREAD

**Issue by jyljyl** [openstenoproject/plover#1052]
## Summary

I checked the COM ports and set them so they match up. The machine is connected. It won't type. It works just fine with my keyboard, but it won't recognize my ProCat. I got cords just for this. I've tried it on 2 computers; one with Windows 10 and the other with Windows 8. Neither will work with my ProCat.

**Comment by gdwaynewarner** [comment]
Hi, Jyljyl.
Which version of Plover are you using?
Which communications protocol is Plover set to, and does that match what your Blaze is set to?
Does the Device Manager tell you which COM port you are using?
Did you try your writer with someone else's system to see if it would work?
... and lastly, did you search the [Plover Google group](https://groups.google.com/forum/#!searchin/ploversteno/Blaze|sort:date/ploversteno/gH1CLgG2JKQ/IrOfSi2qBwAJ)?

**Comment by phsot** [comment]
Any answers to this? Turns out I'm having the same problem!

**Comment by gdwaynewarner** [comment]
I think Jyl has updated to the 4.x version of Plover, and judging by what
I've been seeing in the various Facebook groups we're in, she is doing just
fine with Plover.

--gdw

**Comment by jyljyl** [comment]
Actually, I'm using CaseCat now. I never was able to get Plover to work
with the blaze.

**Comment by gdwaynewarner** [comment]
Bummer, Jyl ...!
Have you tried updating to the 4.X version? The ProCAT communications protocol works great!

**Comment by DavidGraper** [comment]
I have a Blaze that's been working with Plover for years now.  I've been using the latest 3.x stable version ever since it came out -- I have to say that the ProCat protocol works quite well.   Whenever I've experienced problems they've all been related to the USB-to-serial connector.  When I started working with Plover years ago with a busted up $100 EBay Stenograph machine I bought the Gearmo model Serial-to-USB connector with LED indicators so that I could rule out basic connectivity issues quickly (https://www.amazon.com/GearMo-Adapter-Indicators-Windows-Support/dp/B00AHYJWWG/ref=sr_1_15?keywords=usb+to+serial&qid=1574351790&sr=8-15) .   Something about it is built right since it works with every version of Windows and Linux I've tried.   
I can understand your frustration -- when setting up my Blaze at home with another machine I was using a $7 generic Serial-To-USB converter -- I found that Windows would recognize the converter, do the little dance of successfully loading the USB driver, and show it as a COM port in Device Manager -- but it just wouldn't work.  After diddling with it all for half an hour I just got my old Gearmo converter out of the closet, plugged it in, and I was keying with my Blaze in a couple minutes.
My advice is to give your Plover setup another shot -- I know you'd rather be spending the time practicing, but ultimately using open source software pays off.
