### ISSUE TITLE
The letter Å sometimes can't be capitalized

### ISSUE THREAD

**Issue by SeaLiteral** [openstenoproject/plover#1057]
## Summary

The letter Å sometimes can't be output capitalized. It only happens sometimes, and it seems to be some weird state Plover might get into at startup. Several actions, such as scrolling the suggestions window up and down might get Plover out of that state, and then the bug won't happen, at least until Plover is restarted.

This only seems to happen with the letter Å, but I wonder if it's related to this: https://github.com/openstenoproject/plover/issues/1029

## Reproducing

Load a dictionary with entries like these:

` ` `
"A*UB": "{&å}",
"A*UP": "{&Å}"
` ` `

Then try to use the entry that writes Å. It should always write Å, but sometimes it comes out as å. If you use the stroke several times it'll keep outputting what it first wrote. So if it wrote å, it'll keep doing that if you try again. But if you then use the other stroke to write å, it will change something so the next time you try to write Å it'll come out correctly.

## Plover Version and System

Running from source on Ubuntu 16.04

**Comment by user202729** [comment]
This may fix the issue: https://github.com/user202729/plover/tree/possibly-fix-output-capitalization

I believe the issue is that the `index()` may return the wrong index if there are multiple identical symbols, but I can't think of a reason why there might be and the order in the queue is incorrect. So far I have not been able to reliably reproduce the issue, partially because the keyboard mapping is preserved across Plover restarts.

However, this doesn't explain why the issue disappears when the suggestion window is scrolled, for example.

Another reason might be that something (DE/WM?) modifies the keyboard mapping and Plover isn't aware of that.

To help debugging the issue, it might help to run Plover with `-l debug` and post the log file (in `.local/share/plover/plover.log` on Linux) or log output.

**Comment by user202729** [comment]
xdotool also had the same issue. I describe the reason for the bug in [a comment](https://github.com/jordansissel/xdotool/issues/97).
