### ISSUE TITLE
Can I use Plover without a GUI?

### ISSUE THREAD

**Issue by F1LT3R** [openstenoproject/plover#1079]
Is it possible to use Plover without a GUI? IE: on a Linux device with no GUI installed?

How would I do this?

**Comment by Teteros** [comment]
You can use `--gui none` option (at least on plover 4+) which works for daemonized usage but plover is still reliant on xorg server to run.

**Comment by F1LT3R** [comment]
Ok thanks @Teteros 
I found this from Ian Cloud: https://groups.google.com/d/msg/ploversteno/1cJlOU7eJzM/C4cCw5-nFAAJ - which says that it can be run from the terminal. Perhaps that still uses xorg though.

**Comment by F1LT3R** [comment]
@Teteros what function is xorg server playing exactly? I'm trying to establish what a NodeJS port of Plover might look like.

**Comment by Teteros** [comment]
Plover is using hardcoded keymaps from xorg
https://github.com/openstenoproject/plover/blob/master/plover/key_combo.py#L6
https://github.com/openstenoproject/plover/blob/master/plover/oslayer/xkeyboardcontrol.py

Not sure how well you could grab keys from linux framebuffer / virtual console instead, or if it's even viable.

This dependency on xorg is a stopper for #1050 (Wayland support) as well since you'd need to support one of its compositors instead of using xlib.

**Comment by benoit-pierre** [comment]
Even when run with no GUI (`-g none`), Plover still rely on X11 support for:
- the keyboard machine: using the XInput extension to capture/grab input
- simulating keyboard input: detecting the keyboard layout (this is not hard-coded, the list in `key_combo.py` is unrelated) and dynamically patching it for full Unicode support, and using the XTest extension for simulating keyboard events
