### ISSUE TITLE
Fix Learn Plover Link in Wiki

### ISSUE THREAD

**Issue by winstond** [openstenoproject/plover#1088]
## Summary

The link in the wiki and any documentation hosted here should point to this URL:
https://sites.google.com/site/learnplover/

This is as per Zach.  This is the more updated site.

**Comment by mulka** [comment]
@winstond 
It isn't clear to me why that link is better than this link: https://sites.google.com/site/ploverdoc/

It seems like the content is the same, or at least the first part of it. Why are there two copies? Could one of them be removed? Or maybe one linked to the other?

**Comment by mulka** [comment]
Alrighty! Within the last 9 hours looks like Zach updated the old site to point to the new site. I went through the wiki and replaced all the links, but it seems I don't have access to push to the wiki git repo. I'd rather not have to edit them all again in the web editor. Could someone give me access to the project so I can just push this git branch?

**Comment by JRJurman** [comment]
@mulka can you make a PR from your own fork of the repo?

**Comment by mulka** [comment]
@JRJurman So, I guess you can't directly fork a wiki or make pull requests to a wiki, but I did push my copy of the wiki to a new repo. So, maybe someone can just pull it from there. Here's the commit: https://github.com/mulka/ploverwiki/commit/c256760a073c5d188fbe32da17b08d607bea8b9e

**Comment by nsmarkop** [comment]
@mulka I just went through each page manually and edited the links based off of your commit -- do you not have access to edit the pages at all? I think we should be okay now for this issue though.

Doing so did show me that the organization of the wiki pages could definitely be improved though. Like, why are we linking to Learn Plover directly from the Stentura Protege setup and usage instructions page rather than linking to one of the pages about learning stenography or getting started with Plover?
