### ISSUE TITLE
billion million trillion

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#1098]
## Summary

Plover not very good at currency?

## Reproducing

When you type 1 billion, then the meta for currency, nothing happens.  I assume this is cz it's looking for a number immediately to the left.  A number made of numerals, I mean.  I suppose it would work if I typed 1,000,000,000, but who does that?  :-S

Am I misusing it?  Or is there a plugin that handles this?  I didn't see one in the Manager.

Incidentally, the newest version of Plover is freaking amazing, I love it!  It does almost everything I want it to do.  You guys are awesome.

And also incidentally, Ted, if you read this, I reallllllly appreciate your Dictionary Builder plugin.  It works so perfectly, and I was thrilled when I saw a plugin that had this functionality!  Long overdue!

Chris 

## Plover Version

4.0.0dev8

## System

W10

**Comment by mulka** [comment]
Sounds like a good idea!

**Comment by nsmarkop** [comment]
Would you be able to clarify exactly what you expect the currency meta to do when you type "1 billion" and then a stroke for it? Are you wanting "$1 billion", "$1,000,000,000", or something else? Would you expect anything if you typed "one billion" and then the currency meta? 

As it stands right now, those aren't use cases that the currency meta is meant for. You can see its description here: 

https://github.com/openstenoproject/plover/wiki/Dictionary-Format#format-currency

And the relevant code for it is here:

https://github.com/openstenoproject/plover/blob/f4e45364fc5f58745c459f878d13ec6442497f46/plover/formatting.py#L843

So, likely this is more of a request for a new plugin unless completely changing the current behavior is on the table.

**Comment by ms009986** [comment]
SORRY!  I thought I finished this a month ago but it turns out I never sent
it.  Hope this is still useful!

----

Well, let's see....

I know (or I think) you guys are more focused on Plover for use by
programmers, but hopefully you are also interested in those of us Plover
users who are ex-steno-software users (like Mirabai) or who have gotten as
fast as they're going to get on a regular keyboard and want to go faster.
:-)

Anyway, I would say that the rules would be something like this.

For the simpler stuff, iIf I stroked just...

1 billion (dollar shortcut) it would come out $1 billion
ten trillion (dollar shortcut) ... $10 trillion
4 thousand (dollar shortcut) ... $4000

...BUT there should be an option in the user's preferences or in the meta
itself that allowed for writing it $1,000,000,000, or
$10,000,000,000,000.00, or four thousand dollars, or $4,000, or whatever
currency formatting the user wishes...preferably in the meta so you could
change it depending on what dictionary you were using.

Like *this *client always wants a comma before 000, but this *other *client
doesn't want one if it's a four-digit number.  You load the dictionary with
the meta set up according to each's specs, and you don't have to do
anything different, just steno what you hear and the currency formats
correctly.


Then the more complicated numbers should come out...

4 hundred thousand (dollar shortcut) ... $400,000
400 thousand (dollar shortcut) ... $400,000
1 billion 86 million 42 (dollar shortcut) ... $1,086,000,042
(for clarity because $1 billion 86 million 42 is basically unreadable)
1546252310 (dollar shortcut) ... $1,546,252,310

39 thousand four hundred 62 and 38 cents ... $39,462.38

(just in case you're a very inconsistent stenographer)


That's roughly it. Glad to clarify further!  I promise to not take so long
next time!

Chris

PS.  Also there should be a setting so where if you stroke eight, six, ten,
four, etc., the meta lets you specify that in your dictionary to come out
eight, six, ten, four
or
8, 6, 10, 4
or
eight, six, 10, four
(some people disagree on whether or not a 10 should be spelled out).

It could be argued that the stenographer should just stroke it differently
depending on the client, but personally I can't always remember the
client's formatting while I'm stenoing, and even if I do I might not
remember to stroke it that way when I'm "in the zone".

PPS.  But strictly speaking that's not currency, so if you want to skip
that for now I won't push my luck.  :-)

**Comment by ms009986** [comment]
Sorry again!  I hadn't heard anything on this topic, so I checked it while I was here and I noticed that my whole message was hidden under a history ellipsis, so I deleted my line of hyphens which apparently invoked that ellipsis against my will.  So I DID answer the question eventually, it was just hiding from you!  Hopefully you can see it now, if you thought before that I never answered the question.

**Comment by gdwaynewarner** [comment]
In Phoenix Theory, numbers as words are written with an asterisk, like so:

W*-UPB

Take out the asterisk, and you get the number.

One of the outlines for the word "thousand" is defined as TH-OUPB. Add the asterisk and you get **,000**.

I created a dictionary with outlines for (some of) these, using the Phoenix Theory outlines, which I have attached below as a .zip file.

I also have a screenshot of the Plover outlines for (some of) those big numbers as words. I think only one of them contains an asterisk, but it also has a matching outline without the asterisk, so you can edit that RTF dictionary accordingly ... but due to the issues with RTF dictionaries getting [corrupted over time](https://github.com/openstenoproject/plover/issues/773), you're going to want to create a .json dictionary for them, or copy the outlines to an existing dictionary ... and, of course, you're going to need a "delete space" to the left of the outlines starting with commas.

Here's a screenshot of a few of Plover's "Numbers Written as Words" dictionary:

![Ploverz_Built-In_Numbers_as_Words_Outlines](https://user-images.githubusercontent.com/17680111/112921033-eda2fd80-90be-11eb-8ffd-ec85477a0596.png)


Here's a screenshot of the "Selected Outlines" dictionary:

![Selected_PT_Number_Outlines](https://user-images.githubusercontent.com/17680111/112917714-1c69a580-90b8-11eb-872c-4c26c64ebde3.png)

... and finally, here's a zipped copy of that dictionary:

[PT_Selected_Number_Outlines.rtf.zip](https://github.com/openstenoproject/plover/files/6225593/PT_Selected_Number_Outlines.rtf.zip)

Hmm. I appear to have left out the hundreds, but fortunately, that's an easy fix. 

In Phoenix, the stroke for "**00**" is simply H-PB. In the copy of the Plover dictionary I have, it's O-Z.

Finally, apparently my Phoenix Theory dictionary doesn't have any outlines for trillions ... but then again, it's from 2014. There's probably something available to download .... anyway, hope this helps fix those number woes for you!

**Comment by greenwyrt** [comment]
Features implemented in  [plover_number_format plugin](https://github.com/Volensia/plover_number_format)
