### ISSUE TITLE
"PBLG" strokes not translating in Plover 3.1.1

### ISSUE THREAD

**Issue by files258login** [openstenoproject/plover#1127]
"PBLG" strokes never translate to anything in Plover 3.1.1

I've created a test dictionary called "test.json with a single entry:

{
"PBLG": "test"
}

After activating Plover and typing these strokes, Plover returns "-PBLG", never translating it to "test" or anything else. 

Plover 3.1.1
Windows 10

**Comment by Kaoffie** [comment]
Due to there being duplicate keys on both sides of the steno layout, a hyphen is used to distinguish the left side and the right side when no vowels are present. Hence, `P` is on the left whilst `-P` is on the right. 

Similarly, for the stroke where the four keys PBLG on the right side are pressed, you'd need a hyphen for disambiguation. The entry should work if you swap `"PBLG"` in the json with `"-PBLG"`.

**Comment by files258login** [comment]
Yes, it worked indeed. Thank you.
