### ISSUE TITLE
macOS: Requires granting Accessibility access to env (security issue)

### ISSUE THREAD

**Issue by Peeja** [openstenoproject/plover#1134]
## Summary

In macOS Catalina, there are stricter security requirements than in previous OS releases. Plover requires Accessibility access in the Security & Privacy settings to work. However, the actual keyboard emulation appears to be attributed to `env`, and so [`env` must be given Accessibility access for Plover to work](https://github.com/openstenoproject/plover/issues/1131). But this means that another process could use `env` to perform malicious actions.

Ideally, the keyboard emulation should be attributed to Plover itself. Failing that, it should be attributed to a Plover-specific helper process so that the user doesn't have to grant access to something as powerful as `env`.

## Reproducing

1. Install Plover on Catalina.
2. Try to type with it.
3. See prompt to give access to `env`, and no output.
4. Enable access for `env` in Security & Privacy.
4. Typing now works.

## Plover Version

weekly-v4.0.0.dev8+66.g685bd33

## System

macOS 10.15.5 (19F101

**Comment by fourshade** [comment]
I don't know much about macOS, but it appears [the launcher](https://github.com/openstenoproject/plover/blob/master/osx/app_resources/plover_launcher.sh) is a simple bash script whose only job is to call into Python. Apple changed the default shell *away* from bash in Catalina, so it's possible that `env` is getting more involved than it should here.

(if I actually *had* a mac I'd probably mess with this...it *feels* like a one-line fix on the shebang line, but keeping it compatible with the previous macOS releases might end up taking a lot more)

**Comment by Peeja** [comment]
Yep, that does seem to be the line. I think the change to `zsh` is a red herring here, though. I think the problem is just that when the package executable is a shebang script, macOS attributes the access requests to the underlying executable that it calls, and requiring Accessibility access at all for what Plover does appears to be new in Catalina. (That is, I never had to give anything permissions before, even the actual Plover app.)

I wish I understood more about how macOS determines which process in the ancestry tree is responsible for an access request, but I have no idea.

**Comment by gdwaynewarner** [comment]
Fourshade, if you have an extra ~$300 lying around, check your local Craig's List or a few of the local pawn shops (make sure it works first!) for a MacBook Pro from around 2012 -- or take your pick from [this list](https://support.apple.com/en-us/HT210222) -- and buy one. Cheapest way to buy a Mac these days -- though around here, Macs are in short supply, most likely because of a certain stimulus check and virus-induced unemployment benefits.

**Comment by rainbowbismuth** [comment]
As a hack/workaround, I renamed the Plover script in the .app to PloverPy, then made a new executable called Plover to put in the same spot that does this:

```c
#include <unistd.h>
extern char **environ;
int main(int argc, char *argv[]) {
    execve("/Applications/Plover.app/Contents/MacOS/PloverPy", argv, environ);
}
```

It started up just fine, and it shows up as Plover in the Security & Privacy dialogs as expected, typing works etc. I know so little about MacOS thats not the same-as-linux subset, more or less, but I really wanted to try 4.0 without giving env that permission. Perhaps the solution could be to grow a tiny C program that replaces the shell script entirely?

**Comment by ThaiWood** [comment]
Thanks @rainbowbismuth, this worked for me as well!  

It does break for me on OSX (10.15.3) if you have some stroke bound to `{PLOVER:LOOKUP}` since the applescript used to get the pid of the window won't have permissions and will get some long text error message instead of the pid. 
 See: 
https://github.com/openstenoproject/plover/blob/26aacfa829bd9625b65c056d94250064a5fa2f0d/plover/oslayer/wmctrl.py#L18-L21

I tried several workarounds, but the permissions the applescript needs is "automation" permissions and not accessibility, which seems to be less usable.  I even tried resetting all the automation permissions with `tccutil`, but I still couldn't get them to be requested.   Making a "true" app out of the applescript doesn't work because though compiled (non-app package though) applescripts can still write to STDOUT, it seems app packages force a GUI only run, though it _does_ request perms.  Similarly `osascript` invocation of the same applescript or even of an app package has the same limitations as the python launched applescript.

I'm not really sure what the right fix is here, I'm in a similar boat with my osx knowledge and know very little python as well.  I know the PID of the front window can be gotten from `lsaappinfo`.  But I'm not sure how long that has shipped with OSX.  So something (ugly) like:

```
process = subprocess.run("lsappinfo info -only pid `lsappinfo front`", shell=True, capture_output=True, text=True)
return int(process.stdout.strip("\"pid="))
```

But I'm not aware of a non-applescript way to switch windows for the second part of `wmctrl`.  I think there are probably a few different ways this could go and I'm not sure what project folks would prefer:

1. Leave things as a they are, all features work this way, but then security is compromised.
2. Go with small launcher binary and disable wmctrl functionality for osx. Window switching won't work for you, but it won't crash.
3. Write some larger binary that can launch and do some window control stuff.  I don't know how this would work, but some older [apple sample code](https://developer.apple.com/library/archive/samplecode/SonOfGrab/) makes me think its _possible_ at least.

**Comment by morinted** [comment]
I think finding a good way to request and get permissions is ideal. I'm okay with the launcher option if that's what we need to do. Are you interested in trying to PR a solution to this?

**Comment by morinted** [comment]
Wondering if py2app handles this nicely. I built an example app and they have a symlinked python right next to an executable and I'm not exactly sure how they make it. https://github.com/ronaldoussoren/py2app

**Comment by morinted** [comment]
My inclination would be to convert plover_launcher.sh into a c file and build it during the app creation. All that plover_launcher does is run python with some arguments, forwarding whatever people provide if they launch it manually (through terminal like `/Applications/Plover.app/Contents/MacOS/Plover my_command_here`)

Maybe the permissions would be less dodgy if we did it that way, rather than using the executable to launch a shell script to launch python (assuming that c → python might give proper permissions where c → shell → python doesn't)

c's a weak point for me, so I'd love to get all the assistance I can on this one.

**Comment by morinted** [comment]
I'm making progress on this. Turns out the permissions dialog for automation requires a PList entry called `NSAppleEventsUsageDescription`

At one point I thought I was clever and replaced the apple script with 

```python
    from Cocoa import NSWorkspace, NSRunningApplication, NSApplicationActivateIgnoringOtherApps

    def GetForegroundWindow():
        return NSWorkspace.sharedWorkspace().frontmostApplication().processIdentifier()

    def SetForegroundWindow(pid):
        target_window = NSRunningApplication.runningApplicationWithProcessIdentifier_(pid)
        target_window.activateWithOptions_(NSApplicationActivateIgnoringOtherApps)
```

I'm just archiving this code here because I didn't end up needing it, but maybe one day…

**Comment by morinted** [comment]
Okay, PR opened with my embarrassing C code 🙈 

A test build from circle CI is available to try, I've [reuploaded it to Google Drive here](https://drive.google.com/file/d/1_ycfe3WyCadwheWAMRW81WMlQd8Tx29W/).

Please let me know if this fixes the issue on your machines!
