### ISSUE TITLE
Priority of keyboard shortcuts (macOS)

### ISSUE THREAD

**Issue by ayroblu** [openstenoproject/plover#1143]
## Summary

Hey, I'm learning plover just recently and I downloaded Ted Morin's spectacle pack: http://www.openstenoproject.org/stenodict/dictionaries/spectacle.html

I tried to use the left half and right half shortcuts e.g. `{#Alt_L(Super_L(Left))}`, but in chrome they use the underlying chrome shortcut of moving left and right between tabs. However, if type this out manually on my keyboard (`cmd` + `alt` + `left`) then it behaves as expected.

Obviously there's some priority business between the commands plover sends and how we enter it on the keyboard and I was wondering if there's any insight or possible fixes for it?

## Reproducing

Use spectacle default settings
Dict:
`"SP-FR": "{#Alt_L(Super_L(Left))}",`
Try use it in chrome, then type it out manually with `cmd` + `alt` + `left`

## Plover Version

3.1.1

## System

macOS

**Comment by gdwaynewarner** [comment]
If you are running Mac OS 10.10 or above, I highly recommend downloading the current pre-release version 4.x, which you can find here:
[https://github.com/openstenoproject/plover/releases](https://github.com/openstenoproject/plover/releases)

When you download and install it, you will have to control-click the new version of Plover and select Open; otherwise the Gatekeeper will activate and not let you run it, because it sees it as being from "... an unidentified developer."

It might also be a good idea to compress the old version before installing the new version in case the new version doesn't work for you (it should -- assuming you're running Mac OS X 10.10 or higher).

**Comment by ayroblu** [comment]
Works thanks! Any idea when this "pre-release" will become a release? It's been 2 years 😛
