### ISSUE TITLE
Missing letters on Ubuntu

### ISSUE THREAD

**Issue by reflective-carillon** [openstenoproject/plover#1175]
## Summary

 Plover sporadically fails to type letters in the middle of a word, or fails to completely delete a word.

## Reproducing

The bug is intermittent. For example, repeated K-P followed by repeated * might eventually give "  company co", because it failed to delete some letters from some of the "company"s. I'm not sure if the initial extra spaces are part of this bug or not. Another example: repeated SWR- just gave me " Somewhere somewhere somewhere somewhere somewhere somewhre somewhere" — the sixth word is missing its second "e".

## Plover Version

Plover 4.0.0.dev8+66.g685bd33 

## System

On Ubuntu 18.04.5 with Plover installed from ppa:benoit.pierre/plover.

**Comment by aerickt** [comment]
Is this on Wayland or X?

**Comment by reflective-carillon** [comment]
X

**Comment by user202729** [comment]
Although it's not clear what the problem is exactly, you can run from source, merge pull request 1132, and set the delay between sent key presses to some reasonable value, then the issue will usually be fixed.

There have been several issues about the same bug (1071, 1051, 1059, the last one is LibreOffice-specific and not Plover-specific)

**Comment by antistic** [comment]
#1071 #1051 #1059 for backlinking

**Comment by SeaLiteral** [comment]
This sounds kinda like #1408 which got fixed? Has it somehow been reintroduced in a newer version of IBus? Well, I'm actually getting this issue too (and I would have had a "typo" in this comment if I hadn't fixed it manually)

**Comment by SeaLiteral** [comment]
Well, maybe not specifically an IBus issue, but I'm nnot sure it's Firefox or LibreOffice directly either. The issue seems to happen on GNOME but not on LXQt. There's also the issue that Xorg seems to be crashing sometimes when I'm using Plover, and debugging that might theoretically be easier if it happens on GNOME. So I'm guessing I'll use LXQt most of the time and maybe use GNOME sometimes and "hope" Xorg crashes then.

**Comment by daaang** [comment]
I was having this issue expressing itself in different ways:

1. In Firefox, it would miss letters (e.g. typing somewhere 10x might yield: somewhere somehere somewhere somewhere somewhere somewere somewhere somwher somewhere somewhre). This was especially frustrating, since it broke delete.
2. In chromium and obsidian (which is electron), it never missed a letter but letters would go out of order (somewhere somewhere smoewhere somewhere somewhere somewhere somewheer somewhere somewheres omewhere). At least delete works.
3. In slack (also electron, so ???) and hyper, Plover has worked perfectly always.

Reading through a few issues linked from here, I see a lot of people blaming ibus. I figured it probably wasn't that for me, since the behaviors seemed linked to specific applications. However I just ran:

    pkill ibus

And Plover has been working perfectly in every program I use ever since. And it didn't break anything either? Apparently, all ibus does is mess up my typing, but I can't uninstall it because I run Pop!_OS, and having to run `pkill ibus` every time I reboot isn't annoying enough to warrant switching distros.

Since I did get this working, I figured I may as well post what I did in here, the first thread I found.
