### ISSUE TITLE
Use JSON for wordlist file for faster loading?

### ISSUE THREAD

**Issue by user202729** [openstenoproject/plover#1243]
The speedup is about 0.3s. Might or might not be significant...

Although the JSON might have to be sorted in the correct order.

Some alternatives:

* Using pickle instead of json improves another 0.1s.
* Loading and computing the SHA 256 of the whole file takes about 0.05s; which can be used to cache a pickle file (although this might be too much work for little gain)

**note**: this is a breaking change (for existing systems plugin, if they use a word list); however it's possible to only use this feature if the file extension is JSON, to minimize API changes.

**Side note:**

This is mainly noticeable on independent scripts that use Plover as a library.

Although if the typical `registry.update()` method is used, Plover will also load all registered entry points and that takes much more time, depends on which plugins are installed -- for instance, plover_emoji takes 0.65 seconds to load.

**Comment by user202729** [comment]
Note: implemented in https://github.com/user202729/plover/commit/c048f798746737337031a24b4f76f75eed760a27 , but is this a desirable feature?

**Comment by fourshade** [comment]
I certainly think so; I've done benchmarks on Plover startup and wordlist loading eats a lot of time. My fork did something like this:

```
plover/system/__init__.py:25
----------------------------
     with open(path, encoding='utf-8') as f:
-        pairs = [word.strip().rsplit(' ', 1) for word in f]
-        pairs.sort(reverse=True, key=lambda x: int(x[1]))
-        words = {p[0]: int(p[1]) for p in pairs}
-    return words
+        text = f.read()
+    it = iter(text.split())
+    return dict(zip(it, map(int, it)))
```

This splits the entire file on whitespace, leaving a list of alternating fields: [word, rank, word, rank,...]. If you make an `iter`ator and include it twice in a `zip`, it gets polled twice each iteration, which lets it shift out pairs of (word: rank) to make a dictionary. It is somewhat arcane, but it does pass the tests with the current wordlist and runs at 0.124 s vs. 0.573 s on my machine, so I know this section of code can be improved without a breaking change.

**Comment by user202729** [comment]
It's still somewhat-breaking as your version doesn't sort. But that would be a little better (and the order might not be very important).

It's unfortunate that good code might carry additional performance penalty in Python.

**Comment by fourshade** [comment]
In the absence of API documentation all we can rely on is the tests, and that code passes, so I don't consider it breaking. A "word" has no spaces by definition, and an empty string as a word would fail to parse using the *current* code. Parsing speed vs. user-safety is always a trade-off, and this file is Plover's single largest asset by size even without the overhead of JSON tokens.

The sort is pointless since the entire thing gets dumped into a dictionary. The only possible effect it could have is change which priority is kept in the case of duplicate words, which IMHO is actually *worse* than doing nothing. The behavior I would expect from a key/value list like this is that later values override earlier ones if there are duplicate keys; that's the way pretty much any JSON parser would do it. Not only does the sort break this assumption, it wastes startup time in doing so. Try it without the sort.

**Comment by fourshade** [comment]
As it stands there *are* duplicate words in the current wordlist, and that's kind of a black eye in itself. A 100% compatible fix would at least require these things:

1. Purge the duplicate words from the wordlist, keeping the priorities that are kept by the current algorithm.
2. Rewrite the code without the sort. User-added duplicates would work just as if it were JSON from then on.

@Benoit-Pierre is this an acceptable fix? I think we fought over this one before. No arcane tricks this time.

**Comment by benoit-pierre** [comment]
Yes, I think this would be fine:
```python
     with open(path, encoding='utf-8') as f:
        text = f.read()
    it = iter(text.split())
    return dict(zip(it, map(int, it)))
```
once duplicates are removed.

**Comment by fourshade** [comment]
Will do. I think I've got all the pieces I need to put this together now!
