### ISSUE TITLE
Support customizing the steno layout

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#134]
Allow remapping the steno keyboard to represent other letters for looking up outlines in the dictionary. Here is a list of mappings in other languages:
http://www.stenograph.com/pages.aspx?docid=228

**Comment by hhirsch** [comment]
Imho there should be a way to switch dictionaries on and off on the fly. I am sure there are many multi-lingual people that like to use multiple dictionaries.

**Comment by morinted** [comment]
The reordering of keys is programmatically complete. What about spelling rules and suffix folding? Not too sure how we could support custom rules without building different releases. Maybe a simple binary enable/disable would suffice for an MVP?

**Comment by Achim63** [comment]
I'd be happy with the possibility to just switch off the rules for English.
The rules for German would be very complicated I guess, so it's probably easier to just make dictionary entries for all forms.

A simple dropdown list of the key mappings as given on the Stenograph page in the preferences would be really handy. For now I use a little Python script to convert a json dictionary with German entries to the US layout for import in Plover. Would be nice to not have to do this conversion every time a change to the German dictionary was made.

On the other hand: I leave the US dictionaries open when I open my German dictionary (which has less than a hundred entries and is just for testing purposes and maybe developing a full theory one day). Then I have all the entries for punctuation, special keys etc. still available. So it might be even better if the mentioned popup would exist for each dictionary used.

Maybe even easier to implement: make the first dictionary entry a language specifier (optional, defaulting to US), something like "DICTLANG": "DE", "DICTLANG": "FR" etc. and convert it to US layout on import accordingly.

I was about to share the conversion tool on the Plover Aviary anyway, so if somebody wants to have a look into it, I'd be happy to send it to him (be warned, though - I'm not much of a programmer and still using functional programming style, not object oriented - some call it spaghetti code ...).

**Comment by hhirsch** [comment]
@Achim63 It would be really interesting to hear more details about how you use plover and your dictionary. Maybe write a big readme when you publish your conversion tool?

**Comment by morinted** [comment]
@Achim63 I agree, a gist with all of this information would be cool. Also, love functional (unless you are lying and are using loops) so that's no issue. :p

By the way, Achim, not sure if you noticed, but at some time in the recent past, as you can see in [this file](https://github.com/openstenoproject/plover/blob/c2fb4e7ecde7e18551a830bb5d4976343a4cfb0d/plover/assets/main.json), check out line 2197

**Comment by Achim63** [comment]
Ha! Nice! I use just KHEUPL ;-)

**Comment by morinted** [comment]
This is coming with much of @benoit-pierre's work. #319 chording systems as well as machine keymap editing.

**Comment by morinted** [comment]
@azizyemloul that's fantastic work you've done with the GrandJean layout. Is it possible to use a regular steno machine to work with the French layout?

**Comment by azizyemloul** [comment]
Ouh! Sorry. Little bit late but yes, definitly. 

Many french stenographers use the more common for you "Ward Stone Ireland" layout machines. It would not surprise me if some are already supported by plover.

That said I had never seen one because I left the Grandjean school and i had not enough time to investigate outside the school where we were restricted to the french layout.

I can add that short time after my departure I had heard that the school stopped in-house manufacturing of the machine and have choosen a US manufacturer providing a custom V shape layout but i have no more informations about it. 

Since this time I have purchased an utopen stenoboard kit but i have not the adequate material to assemble it.

Lastly, I want to thank you very much for  your work on this project. It was very exciting for me to see how it could be extended. I think that giving it a french gateway would help people to work on the linguistic part of the project and make plover spread significatively in France.

**Comment by morinted** [comment]
I've opened an issue for the Grandjean system, please redirect development on that to #781. In the meanwhile, thanks to @benoit-pierre Plover does support customizing the layout through plugins.

**Comment by user202729** [comment]
@Zireael07 Write a system Plover plugin. Refer to https://plover.readthedocs.io/en/latest/plugin-dev/systems.html for brief documentation, and https://github.com/openstenoproject/plover_michela for an example.
