### ISSUE TITLE
ERROR: engine on_stroked failed with KeyError: '^' when typing KHR*PB

### ISSUE THREAD

**Issue by Kenny2github** [openstenoproject/plover#1407]
**Describe the bug**

Trying to type a colon with no space after (I think that's what `{:^}` is) fails with an error.

**To Reproduce**

1. Enable Plover output
2. Chord KHR*PB
3. See error

**Expected behavior**

A colon should be produced.

**Screenshots**

![ERROR: engine on_stroked failed with KeyError: '^'](https://user-images.githubusercontent.com/28599280/132441064-5d28f7b2-1aa6-47dd-8d10-d63fb473a291.png)

**Operating system**

 - OS: Windows 10
 - Plover Version 4.0.0.dev10+2.g0501aa3

**Hardware**

If relevant, an EcoSteno v1.0.18 configured as follows:
![Machine configuration](https://user-images.githubusercontent.com/28599280/132441262-f5b8cd84-6c5e-49d5-b922-3f3519036381.png)

**Comment by sammdot** [comment]
In this case, the issue is that the translation is getting interpreted as "run the meta named `^`", rather than "output a colon with a right attachment". Since it doesn't exactly make sense for a colon to be orthographically attached, you can just turn this into a raw attach to work around it:

```
"KHR*PB": ":{^}",
```

I'm not sure whether it's worth actually handling this case in the parsing code -- should the expected behavior be the meta interpretation or the attachment one? Either way, I'd use the raw attachment.
