### ISSUE TITLE
WSL capitalization problems

### ISSUE THREAD

**Issue by Josiah-tan** [openstenoproject/plover#1485]
**Describe the bug**

Essentially whenever I steno something with capital letters in command mode in vim in WSL
<img width="89" alt="image" src="https://user-images.githubusercontent.com/65082231/152958082-9f6941e0-620a-4a46-8ab5-1b98bc1c7af7.png">
weird spaces appear in the terminal (for example, after stroking `HRA*PB` as for LAN)

it also behaves strangely when I use the control J binding in insert mode using the shift command (from [user 2](https://github.com/openstenoproject/plover/discussions/1350))
e.g.
```
{#control(j) shift(A)}
{#control(j) shift(B)}
```

**Operating system**

 - OS: 
<img width="222" alt="image" src="https://user-images.githubusercontent.com/65082231/152962894-1f0a3b0a-d105-4454-a4d8-b558ceeb9629.png">

- Plover 4.0.0.dev10+146.g3e7ba1a

- vim:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/65082231/152963106-147c3c13-059f-447e-95f2-c41a0b8228b4.png">

**Hardware**
probably not needed but let me know if you need this information

**Miscellaneous**

#1410 is probably related to this issue, however it's better than it was before because mistrokes no longer cause a mayhem in the vim editor
note: none of these problems occur in Linux

**Comment by njfdev** [comment]
Hello, I know this is a late response, but I cannot recreate this issue on the newest version of Plover 4.0.0.dev11. Is this still a problem for you or can we close this issue?

**Comment by Josiah-tan** [comment]
Yup we can close it now

**Comment by derekthecool** [comment]
I'm seeing this exact problem using Ubuntu WSL 22. @Josiah-tan, did your problem actually go away for you?

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

Running Windows 11
Tested with Plover versions and both had the same problem
- Plover 4.0.0rc2+6.g53c416f 
- Plover 4.0.0.dev12

Any of my steno dictionary items with the `{-|}` like this one of mine for capital P without spaces around it `{^}{-|}p{^}`.
For example this one from main.json has the same problem
```json
  "AUL/AUL": "all, \"{-|}{^}",
```

My lowercase p does not have any trouble
```
P*         : {^}{>}p{^}
```

But my upper case p does

```
P*P        : {^}{-|}p{^}
```

Messing around I found that this one has trouble

```
TKPWHR-FRPBLG : {^}p{^}
```

And this one does not

```
TKPWHR-FRPBLG : {^ ^}p{^ ^}
```

The last interesting note is whats happens when trying to exit vim with the keys `ESC + q + !`

```
|   KP H              D | {^}{#Escape}:{^} 2024-12-02 11:12:48.372 2>KHR*PB
|   K W    *            | {^}{>}q{^} 2024-12-02 11:12:49.364
| S K WH      FR        | {^}!{^} 2024-12-02 11:12:49.685
```

I see this
```
:q^@!
```

So yeah, just a bit of weirdness going on here.
