### ISSUE TITLE
Add -ach {^s} orthography rule

### ISSUE THREAD

**Issue by hftf** [openstenoproject/plover#1543]
Words like `attach`, `detach`, `spinach` currently get pluralized as `attachs`, `detachs`, `spinachs`.

**Comment by Vermoot** [comment]
I've been looking at the list of words the orthography rules follow (`american_english_words.txt`) and it seems that words ending in "ach" that get pluralized as "aches" might be the exception, rather than the rule.

From what I see, trying with every consonant with "-ach" after it, most of them make a `k` sound, for example "stomach", and those would be pluralized with just an S, and not "es".

I might be wrong, but I think not adding "-ach" to the regex for orthography rules might be better?
