### ISSUE TITLE
Do not output a space when just sending special keys

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#164]
Right now when plover sends special keys like {#Return} and {#Tab} it also outputs a space. Plover should only output a space when actual text is also being output.

**Comment by morinted** [comment]
I think that because the solution is just to modify your commands to include a suffix or prefix (or both) of `{^}`, I will close this. Otherwise we'd have to assign a special command to each special character case to decide whether it needs a space. The Plover dictionary in the pipeline should address this issue for most users.
