### ISSUE TITLE
Cannot install plugins (official Ubuntu 23.04, Plover 4.0.0.dev10) 

### ISSUE THREAD

**Issue by robert-winkler** [openstenoproject/plover#1643]
Hi, I tried different ways to install Plover on Ubuntu 23.04.

Finally, I took the official (synaptic) version, 4.0.0.dev10).
However, I don't find how to install plugins.
For example, I need the system switcher for changing languages.

Before, I used the console Plover and installed everything with the pip command-line.
This does not work anymore since pipx is forced for normal users...

Is there any hint/way to install Plover and the required plugins on Ubuntu? Graphical and command-line methods are acceptable to me!

My recommendation would be to pack the plug-in manager into the Plover main program.

**Comment by sammdot** [comment]
Unfortunately, this is just a side effect of installing Plover through your system's package manager, where it's forced to use the system Python installation. **Bundling the plugin manager won't make a difference**, since the plugins are installed through `pip` either way.

The AppImage release you can download from GitHub is the recommended way to install Plover, since it's much easier to keep up-to-date, and the Python is bundled in so it doesn't install into the system one. Otherwise, I'm not sure there's a workaround I know of besides just force-breaking system packages. 😞

**Comment by robert-winkler** [comment]
Thanks a lot for your quick answer! The AppImage works fine, and I was also able to install and patch the Spanish eo variant plugin.
Now I just need to write faster and build my dictionaries : - ).
