### ISSUE TITLE
Unicode support in output of Plover

### ISSUE THREAD

**Issue by flamenco108** [openstenoproject/plover#179]
I would like to report the problem with Unicode support at output of the Plover. For this experiment I changed the main dictionary for my own:
```json
{ 
"S": "ZAŻÓŁĆ",
"T": "GĘŚLĄ",
"K": "JAŹŃ",
"P": "Ł",
"W": "Ń",
"H": "Ó",
"R": "Ś",
"ST": "Ż",
"SK": "Ź"}
```
A you see, there are Unicode characters assigned to the steno-keys.
Let's see such an input:
> qwerasdf

Which actually meant by steno-keys:
> STPHSKWR

Now I'll show you the output:
>  ZAo GL  o ZAo JA  

It seems like the Plover doesn't process the Unicode characters...

BUT!!!

Look at the log of the Plover:
```
ksmirnow@ubuntu:~/.config/plover$ cat plover.log 

2014-02-14 04:00:20,754 Stroke(S-)
2014-02-14 04:00:20,754 Translation(('S',) : ZAŻÓŁĆ)
2014-02-14 04:00:20,994 Stroke(T-)
2014-02-14 04:00:20,994 Translation(('T',) : GĘŚLĄ)
2014-02-14 04:00:21,242 Stroke(P-)
2014-02-14 04:00:21,242 Translation(('P',) : Ł)
2014-02-14 04:00:21,446 Stroke(H-)
2014-02-14 04:00:21,446 Translation(('H',) : Ó)
2014-02-14 04:00:21,982 Stroke(S-)
2014-02-14 04:00:21,982 Translation(('S',) : ZAŻÓŁĆ)
2014-02-14 04:00:22,206 Stroke(K-)
2014-02-14 04:00:22,206 Translation(('K',) : JAŹŃ)
2014-02-14 04:00:22,446 Stroke(W-)
2014-02-14 04:00:22,446 Translation(('W',) : Ń)
2014-02-14 04:00:22,670 Stroke(R-)
2014-02-14 04:00:22,670 Translation(('R',) : Ś)
ksmirnow@ubuntu:~/.config/plover
```
A you see above, in the log, the Unicode characters are printed correctly.

This means (in my humble opinion, but I'm not a computer programmer), that Plover actually processes the Unicode correctly, but something is wrong with the output.

This experiment was made on freshly installed version 2.5.8 of Plover, on Xubuntu (fully Unicoded system). I wrote on Leafpad.

I hope, it will help in development of the Plover.

**Comment by morinted** [comment]
I'm going to close this for now as I've had no issue using special characters on OS X and Windows. Linux is not supported due to the limitations in outputting unicode.

**Comment by flamenco108** [comment]
Thenk you...

**Comment by chajadan** [comment]
What linux limitations are those? First I've heard of it, so just asking for my own edification. I would have assumed linux could do it, but I guess their version of sendKeys simply doesn't support it?

**Comment by morinted** [comment]
You can look into the x lib code and the evdev pull request. I think it's mainly the fact that since we are emulating the keyboard, we are not saying "print this character" but rather "use this key code" and there's no key code for emoji or accented characters. I'm not familiar with the Linux code, though, so you can check in the oslayer folder to get a better idea than I can provide.

Also annoying in the Linux version is that raw output is not suppressed (mentioned on another issue) but rather backspaced. If you are wanting, this is a hot issue.

**Comment by benoit-pierre** [comment]
For keyboard suppression on Linux you can look at [my branch](https://github.com/benoit-pierre/plover/tree/bpierre), more precisely those 2 commits: https://github.com/openstenoproject/plover/commit/6aae52c875b5efd0702e35bdbc8971b4fde0b570 and https://github.com/openstenoproject/plover/commit/b512e0822580c0993caea656d6758d3b058d8c9f. I can clean this up and make a merge request if you want: I only grab/suppress the steno keys, not the whole keyboard, not sure if this is the right behavior compared with how the Windows/Mac versions work.

For Unicode support on Linux you can look at this [proof of concept branch](https://github.com/benoit-pierre/plover/commit/b005165ff124d94b9545bfecb8b84cf8deeacf90). I can provide more details on my understanding of the problem(s) and what could be done if you want.

**Comment by morinted** [comment]
Whoa, Benoit, that's great. I'd love a pull request for your suppression
branch and that behavior is the same as OS X and Windows. If you can (only
if it's convenient) you can make it so that if the user is holding control,
super, or Alt, that the suppression stops (helpful for new users).

I'm also quite curious as to how you manage Unicode support and what
caveats are involved.

**Comment by benoit-pierre** [comment]
> Whoa, Benoit, that's great. I'd love a pull request for your suppression branch and that behavior is the same as OS X and Windows.

mmm, the Linux version does in fact work differently than the Windows/Mac version: only the following keys are suppressed:

```
`1234567890-=
 qwertyuiop[
 asdfghjkl;'
   cvbnm
```

So 'z' for example is not suppressed.

> If you can (only if it's convenient) you can make it so that if the user is holding control, super, or Alt, that the suppression stops (helpful for new users). 

It already work like that, keys are only suppressed when no modifier is pressed (except for numlock which is ignored).

Anyway see #259 for handling both.

**Comment by benoit-pierre** [comment]
Back to Unicode support on Linux.

I updated my [proof of concept branch](https://github.com/openstenoproject/plover/compare/master...benoit-pierre:unicode-linux).

The main problem is, as you mentioned, that we can't directly send a character to an application, instead we simulate key press/release events.

So what happens is:

1) character => 2) keysym => 3) keycode+modifiers => 4) keysym => 5) character

with 1-3 done by Plover to simulate a key press sent to the application, which in turn does the reverse: 3-5 to map back to a character.

This in theory mean that we should be able to handle any character present in the current keyboard layout. For example, when using an US international layout (`setxkbmap us -variant intl`), all 3rd (AltGr) layer characters should be supported, like "äåãøÄÅÃØ".

That's not the case with the current version of Plover because `KeyboardEmulation._keysym_to_keycode_and_modifiers` is buggy. [This commit](https://github.com/openstenoproject/plover/commit/7fabcfb2f60f7132641147a514d4e385b70e9510) improves the situation.

That leave us with the case were a character is not in the layout, in which case we can dynamically change the layout like in [this commit](https://github.com/openstenoproject/plover/commit/217ae73dc9a6bd87c8915fd9e4678c3c0264bce6). The problem is changing the mapping is not synchronous, hence the ugly delay I added to the code...

I wonder if we would not be better off using `ctypes` to access the Xkb extension and use it for all keyboard layout handling.

**Comment by morinted** [comment]
I'd be super interested in an XKB extension implementation, but I acknowledge that it is a lot of development. If you are up to the challenge, I'd more than urge you to try it. It's a pretty big limitation that we can't really support full unicode, especially when it comes to other languages, on Linux. If you want to research any potential caveats before developing, you could do that too. Ideally I think that we want it to:

- Block user input
- Output full unicode
- Output modifier keys
- Work in all applications (I'm looking at you, QT and terminal)

I'm not greatly familiar with the x scene so I'm not sure how compatibility fits in, and you can tell the difficulties involved with previous pull requests (such as in the evdev PR)

**Comment by benoit-pierre** [comment]
> We might also consider the issue of Plover getting the order wrong when strokes are output (as seen in Firefox, Vim, Thunderbird). Maybe a small delay (25-50ms) between keys might help?

Is it still an issue? #112 was supposed to fix this. As I mentioned in the comments, there is still a problem when IBus is running, but AFAIK it's a bug in IBus. Any delay we add between keys we'll be felt a lot.

**Comment by benoit-pierre** [comment]
> Work in all applications (I'm looking at you, QT and terminal)

In which QT application does it not work? As for terminal, it does not work in xterm unless you set a specific resource, e.g. in `~/.Xdefaults`: `XTerm*allowSendEvents: true`. Is that what your referring to?

**Comment by morinted** [comment]
I haven't used Plover on Linux for about a year, so instead of working off
my poor memory, I'll just see how things go when I try it out on an *ubuntu.

**Comment by benoit-pierre** [comment]
I have a working version!

See here: https://github.com/benoit-pierre/plover/compare/bpierre...benoit-pierre:unicode-linux

I'll make a pull request once the other pull requests touching `plover/oslayer/xkeyboardcontrol.py` are out of the way, but I would appreciate some feedback if anybody want to test this.

**Comment by morinted** [comment]
*So awesome*. You are doing really great stuff. I'm very excited to get all these changes in -- once I'm done working on Stenodict (hopefully only a couple days), I'll be back on Plover in the evenings.

**Comment by benoit-pierre** [comment]
Great. I also have 2 other things that can be interesting:

- a new version of my [xinput branch](https://github.com/benoit-pierre/plover/compare/bpierre...benoit-pierre:xinput-keyboard): switch to XInput2 extension for capturing the keyboard input (including grabs). No change in Plover behavior (the code is a little simpler), but: changing the device id in the code makes it possible to only capture/grab one keyboard, so we could add this option to the config/gui (on Linux)

- I implemented Rafael Quintana "Mecatipia" theory for Spanish ([github branch](https://github.com/benoit-pierre/plover/compare/bpierre...benoit-pierre:mecatipia), [windows test build](https://drive.google.com/uc?export=download&id=0B9Je8TDYCh1xbnVLNVZRZHAtdE0
)), and to do that I added [support for "Python" dictionaries](https://github.com/benoit-pierre/plover/commit/31963f6ce78dbbe82aeb33af42c75efc3b17396f) (e.g. [mecatipia.py](https://github.com/benoit-pierre/plover/blob/mecatipia/mecatipia.py))

**Comment by defunkydrummer** [comment]
I'm having the same issue: accented chars like á, é, í, ó don't show.  This makes it useless for spanish!

Version i use: 4.0.0.dev8+66.g685bd33

**Comment by user202729** [comment]
@defunkydrummer  Please report a new issue. With more information on what exactly are you doing, your operating system, other relevant info.
