### ISSUE TITLE
slowdown in 2.5.8

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#189]
Lindsey reports:

Hi there!

I use Plover with a Macbook pro, latest verson of OSX.  I use a Cybra using a serial to USB adapter using the TX Bolt protocol.   I haven't updated Plover in a long long time, so I thought I'd see what was up.  I saw that V 2.5.8 was up so I downloaded and installed.  Everything worked fine for about the first 10-20 strokes then everything s l o w e d way down.  Like stroke - wait 2 full seconds - it shows up on screen.  SLOW.

I fiddled with settings and whatnot, but nothing seemed to change it.  I would mess with something, it would be fine for about 2 minutes and then back to being very very slow.

I gave up and installed 2.5.7 instead, but I wanted to put this out there to put it on the radar.  I know that the update from 2.5.7 to 2.5.8 had something to do with the TX Bolt protocol, and for me at least, something went horribly wrong.  2.5.7 is completely fine for me, no slowdown issues at all so whatever happened between those two versions is the culprit.

Thanks!

**Comment by morinted** [comment]
I'm not sure how to reproduce this. At the moment, I lack a stenomachine with serial protocol to test locally.

**Comment by Achim63** [comment]
I had that happen to me as well a few times, also with a Cybra and TX Bolt mode.
I don't know if this is related, but I also get this slowdown after not using the machine for some minutes, leaving it on. Then it takes several seconds until the stroke appears – though, if I do another stroke, both appear immediately after that second one. This might be some function of the machine itself – some "sleep mode" or similar, so that it only starts sending out data after at least two strokes …
Unfortunately the PDF documentation of the Cybra is very "basic". I don't even know what all the buttons on it are supposed to do. By trial and error I found out that the third and fourth buttons together not only clear the internal memory, but also send out all of it. You better don't have Plover on when doing this, especially if you used strokes like "Cmd+s" in between – luckily I have a good backup system ;-).

**Comment by morinted** [comment]
This issue doesn't crop up often, maybe it's Cybra-specific? I'll close it for now, wondering if it's a hardware problem.

**Comment by Achim63** [comment]
I guess we should leave this issue open - I had the exact same behavior that Lindsey reported a few times today, with the latest OSX build. I then tried 2.5.7 for a while and it didn't happen with that build. So I think it's actually a regression bug in Plover.
