### ISSUE TITLE
portable plover breaks when drive names change

### ISSUE THREAD

**Issue by balshetzer** [openstenoproject/plover#214]
Plover stores absolute paths in the config file, this breaks when the external drive gets a new name. This can be fixed by storing paths relative to the config file.

**Comment by morinted** [comment]
Was this done? If not, it seems important to do because then Plover would be fully useable off of cloud storage.

**Comment by benoit-pierre** [comment]
I took a pass at this: https://github.com/openstenoproject/plover/compare/master...benoit-pierre:config-relative-paths

When a path in the config (log, dictionaries) is relative, it's assumed to be relative to `CONFIG_DIR`.

When setting a config path, it's stored as relative when bellow `CONFIG_DIR`.

**Comment by morinted** [comment]
I think that that's the right way to go. It would need to be documented, but it makes sense. The current behavior is that a config next to the Plover executable make Plover portable, right? You're saying that if I added `../dictionaries/dict.json` that that would be stored as `/home/ted/steno/dictionaries/dict.json`, right? What if it stored relative if, 1) Plover is next to its config and 2) the dictionary is on the same drive?

I can definitely see someone having a dictionary directory not under Plover's folder, however I *don't* think its necessary to code around it since we can just declare that dictionaries have to be in the same folder as the Plover executable.

**Comment by benoit-pierre** [comment]
Another case that is handled by this change (beside portable plover) is simply to be able to version control `~/.local/share/plover` and use it on multiple machines without 
worrying about my home directory being different:

```
[Dictionary Configuration]
dictionary_file1 = main.json
dictionary_file2 = commands.json
dictionary_file3 = user.json
```

**Comment by morinted** [comment]
That's true. I'm very excited to be able to store Plover.dmg and Plover.exe in a folder on Google Drive next to my dictionaries. Less fuss than it is right now.

**Comment by benoit-pierre** [comment]
And yes, if you put `../dictionaries/dict.json`, the next time the config is saved it will be changed back to an absolute path. `dictionaries/dict.json` would work (any path bellow the configuration directory).

**Comment by morinted** [comment]
Is it below or below and next to? i.e. does `./dict.json` work? Err, also do you store as `./dict.json` or `dict.json`?

**Comment by benoit-pierre** [comment]
`./dict.json` works, and is converted to `dict.json` the next time the config is saved.

**Comment by morinted** [comment]
Good to know. Well, I am excited for this change too. Thanks for all the work you've done on Plover lately. You are rocking the steno-world :D

**Comment by benoit-pierre** [comment]
See #305, rebased on master to take care of conflicts.
