### ISSUE TITLE
Plover can't write into secure input fields on OS X

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#247]
This is by design in OS X, secure input fields are meant to prevent any intermediate programs from reading key strokes into the active program. You can read about secure input in [Apple's documentation](https://developer.apple.com/library/mac/technotes/tn2150/_index.html)

Text expander also has an [interesting post](https://smilesoftware.com/TextExpander/secureinput.html) on secure input.

KeePass seems to work with password fields on OS X, so maybe there's something in their code we could look at. Here's [a forum post](https://www.keepassx.org/forum/viewtopic.php?f=5&t=1920&sid=3f8edc6f395e8888d0f76e1e6d9da8ef) that may give some timelines to see when the code for OS X auto-typing was added.

Edit: Synergy must have also solved this issue at some point, and I think that they use Quartz APIs.

**Comment by Achim63** [comment]
Using Applescript it's possible to let the SecurityAgent type into those fields (I just tried). So a workaround using Applescript might actually be possible if you can determine if one of those secure input fields is currently selected.

**Comment by morinted** [comment]
Hi Achim, can you show us the script that you are using?

**Comment by Achim63** [comment]
It was this one to acces a password field in System Preferences/Accessibility (the one that you also need to give Plover accessibility rights), the dialog has to be already open and your password in the clipboard (you can probably also send single keystrokes instead of using the clipboard, since the return stroke was also accepted):

tell application "System Preferences" to activate
tell application "System Events" to tell process "SecurityAgent"
    set value of text field 2 of window 1 to the clipboard
    keystroke return
end tell

**Comment by morinted** [comment]
Okay, so turns out this is for documentation #261. In NKRO mode, Plover can't grab the qwerty input and therefore cannot write into password fields. The workaround on a QWERTY keyboard is to type in your password letter by letter. Real steno machines using a serial protocol are not affected by secure input fields and still work. Phew!
