### ISSUE TITLE
Suggestions on Suggestions

### ISSUE THREAD

**Issue by ms009986** [openstenoproject/plover#297]
Regarding the Suggestions window by @balthamos on my version of Plover:

I am finding that the suggestions window is not all that helpful in that it only shows you the last stroke you made.  The practical result of this is usually when I finish a sentence and look at it it is showing me alternate ways to stroke a period most of the time.

And the default window size takes up a lot of screen real estate to do this.  This window size could just be arbitrary, but I'm thinking possibly it is that long to accommodate a stroke that might have a lot of different alternatives?

I don't think this is very useful, as it's rare to have more than two or three alternatives for a stroke, if that.  But here is how it could be.

If instead of showing the last stroke only, it showed you the last, say, twenty strokes you made and alternatives for stroking that phrase, that would be infinitely more helpful.

A layout like the attached would be ideal, off the top of my head.  It's very rough but you get the idea.  I like the bold, larger type to quickly find the entry you're interested in, and then the alternatives in smaller type, with lines to separate each entry.  It would (hopefully) fit in the existing window and show the last seven or eight entries without you having to scroll, which would be ideal most of the time.

If the twenty strokes were too much to fit in the window ,then the window would become scrollable so that the most recent strokes and alternatives were at the top, but you could scroll down to see older entries.  A new stroke would return the view to the most recent stroke.

Past twenty you probably wouldn't want to keep scrolling, so the entries would age out and disappear.  But if it weren't particularly memory-demanding, it wouldn't hurt to have more than twenty results in the window.

Maybe the entry and the stroke should not appear on the same line in case you stroked a phrase or something and they wouldn't both fit.  Maybe just have the stroke you used be the first entry and alternatives after that?

Chris D  

![for ted](https://cloud.githubusercontent.com/assets/14944833/11055523/0c4c997c-8746-11e5-8b89-bbbc3f592090.PNG)

**Comment by balthamos** [comment]
> And the default window size takes up a lot of screen real estate to do this. This window size could just be arbitrary, but I'm thinking possibly it is that long to accommodate a stroke that might have a lot of different alternatives?

Yes, the window is rather large to accommodate long phrases and many suggestions. Not needing to scroll was the driving factor for the window size.

> If instead of showing the last stroke only, it showed you the last, say, twenty strokes you made and alternatives for stroking that phrase, that would be infinitely more helpful.

This is easier said than done. For a single stroke, there are actually quite a few suggestions displayed. It first tries to build the longest phrase possible that exists in your dictionary. Failing that, it lists words that you may or may not have been trying to stroke (CAT vs cat). Finally, it will show various prefix and suffix combinations, for example, if you mistakenly stroked A instead of AEU.

The tool was targeted more towards a teaching aid and/or productivity enhancement; you would be stroking a phrase and have instant feedback on how to stroke more efficiently, or have a rough reference for stroking similar words. At some point, you would be proficient enough to not need the suggestions anymore and simply close it.

It sounds like the idea you are describing is for more advanced users. Essentially, just a running log of the longest phrases constructed with no information on the constituent words. The current implementation does present this information, but as you pointed out, you need constantly watch the window to see that.

> Past twenty you probably wouldn't want to keep scrolling, so the entries would age out and disappear. But if it weren't particularly memory-demanding, it wouldn't hurt to have more than twenty results in the window.

The memory impact is minimal. You could easily grow the list to over 10,000 entries with negligible impact on memory usage. Presenting the information in an easily browsable form, on the other hand... :)

**Comment by morinted** [comment]
@benoit-pierre is working on an implementation which is very simply keeping a list https://github.com/openstenoproject/plover/pull/296

**Comment by morinted** [comment]
I think this is done, with #296 merged.
