### ISSUE TITLE
Entries that start with an apostrophe should be capitalized if it's after a period or a capitalization command

### ISSUE THREAD

**Issue by stanographer** [openstenoproject/plover#394]
## Summary

Dictionary entries that start with an apostrophe should be capitalized if they're used at the beginning of a sentence, after a punctuation that necessitates a capitalized letter immediately after, or after a capitalization flag.

So if the entry is ['cause], then if I wrote the sentence, "So we should go with option B. 'Cause that was..."
the C in 'cause should be capitalized.

Accordingly, if there's a speaker marker:

MIRABAI: 'Cause that's...

same thing.

## Steps to Reproduce

Write 'cause after anything that would normally immediately be followed by a initially-capitalized word.

## Version

Plover version 2.5.8 with tweaked settings for reduced transposition errors.

Installed via: Ted

## Configuration

OSX 10.11.3

**Comment by morinted** [comment]
The sketchiest workaround you'll ever see: `causea{#BackSpace Alt_L(Left} apostrophe Alt_L(Right)`

Maybe we could implement this as {'}, an apostrophe that doesn't affect capitalization.

**Comment by morinted** [comment]
Okay, I tried to make it a new "meta" punctuation; a leading apostrophe, that shouldn't affect capitalization.

Use it like:

`"KA*UZ": "{'}cause"`

Only use it for leading apostrophes, because it attaches to the following word!

[Download .dmg](https://drive.google.com/file/d/0B_4v0_ER8UlwTUdNNUdoU2N0TWc/view?usp=sharing)

Can you think of other characters that this functionality would be useful for? Would you want an equivalent {"} for quotation marks after a period?

**Comment by morinted** [comment]
Alternatively we could just make meta quote carry capitalization, so `{'} and {"}` are just quotes that don't affect capitalization. It would be up to the user to handle their own spacing, e.g. `{'}{^cause}`. That would allow the use of, for example, `"KW-GS": "{\"}{^}",` and `"KR-GS": "{^}{\"}",`

**Comment by stenoknight** [comment]
That seems like a nicely flexible solution.

**Comment by morinted** [comment]
Maybe it would be better as a "carry capitalization" operator...
Like {~content}
So {~(} and {~'} and {~"} all work.

- `"{~'}{^cause}"`
- `"KW-GS": "{~"}{^}"`
- `"PREPB": "{~(}{^}"`
- `"TKPW-PL": "{~«}{^}"`

Might be more flexible this way, considering that there are quite a few types of delimiters.

**Comment by morinted** [comment]
I played with this a little more today, and I've come up with some discoveries.

So, the reason the syntax in the above post won't work is that the attach flag, "^", explicitly sets things to lowercase, which is why "TK-LS" works pretty well for going back to lowercase. Given that, I can't change the behavior of the attach flag, so instead I lumped it into this change. I also had to modify the syntax to be a little less likely to be accidental. Here's what I've got, using Markdown italics (\* \*):

```json
{
"PH-FPL": "{~|*^}",
"PH*FPL": "{^~|*}",
"KW-GS": "{~|\"^}",
"KR-GS": "{^~|\"}",
}
```

With those, I can now use those to make the following sentences:

*Hello! How are you today?* I'm doing *pretty well* myself. What do **you** think about stenography? **You** better say it's great!

It's neat that it works with doubling and stuff. Could definitely make a lot of useful strokes while coding and Markdowning with this stuff, because you can fearlessly start sentences with \*\*\* for bold italics, without needing to think about capitals and stuff. Same with bullet points…you could have a visual tab that doesn't affect capitalization (for soft line breaking while writing text).
