### ISSUE TITLE
OS X CGEventPost calls send out of order, causing transposition errors

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#413]
## Summary

When writing on OS X ever since the key code upgrade, every now and then letters are "sawpped" in output.

Here are some unordered scratch notes on the issue:

- #412 does not fix this problem.
- It seems to occur after a break -- unlikely in the middle of a sentence, more likely after a pause in writing, near the beginning of a sentence.
- I tried to debug by adding some print messages, but they seem to slow down the output enough to solve the problem such that it won't occur anymore.
- Python sleeps eventually cause a hang in the output.

**Comment by tkpwaeub** [comment]
Thanks for looking into this. Some thoughts:
1. How much of a slow down did you have when you added the gratuitous prints? If it wasn't significant, maybe that suggests a work around. It wouldn't close the bug, but it might lower the priority.
2. If this is caused by adding the keycode support, mainly for quartz applications, as an end user I'd be happy with mostly raw steno out put. This is especially true with anki, where I'm mainly concerned with training my fingers and verifying that I've stroked the correct thing. I don't need the full power of Plover for that. Some sort of "lite" mode would be adequate for my purposes.
3. Could this have something to do with this issue?

http://lists.apple.com/archives/quartz-dev/2009/Oct/msg00087.html

And could his solution work for us?

**Comment by morinted** [comment]
Hey @TKPWAEUB, checkout #412, I've updated it with a build for you to try, tried to change something, maybe it'll work?

**Comment by tkpwaeub** [comment]
Thanks Ted, I'll check it out!

**Comment by tkpwaeub** [comment]
Still getting transpositions. Not as many, but still getting them.

**Comment by tkpwaeub** [comment]
I'm afraid it didn't work. Let me know if there's any more testing I 
can help with.

**Comment by morinted** [comment]
@tkpwaeub how frequently do you get these things? I'm seeing one maybe once every couple of hours… Do you see them much more? Maybe you're on a slower machine? This issue is very annoying…

**Comment by tkpwaeub** [comment]
I was getting it once about twenty minutes or so, and sometimes in “jags.” Also it seems to be more common for some words. So many moving parts here.

Not on a slower machine, but I’m a lot slower than you (for now) so that could be a factor. Hard to come up with a really credible test suite here, isn’t it?

**Comment by morinted** [comment]
Hi @tkpwaeub 

Please try [this build](https://drive.google.com/file/d/0B_4v0_ER8Ulwd2hNTHdTQ3FYVHc/view?usp=sharing) with a half millisecond sleep on non-modifier key down. It's messy, but I'm curious to see the results for you.

**Comment by tkpwaeub** [comment]
It's looking pretty good so far... No transpositions so far tonight, and it's been a few hours now

**Comment by morinted** [comment]
Tentatively closing with #412
