### ISSUE TITLE
Switching keyboard layout on Windows after start breaks special characters

### ISSUE THREAD

**Issue by Tarmean** [openstenoproject/plover#415]
Classification: Bug

Reproducibility: Always

## Summary

Generally special characters work fine but if you change the keyboard layout after Plover is already started it types the characters that would be in that position on the new keyboard.

## Steps to Reproduce

Start Plover
-  After start  on qwertz : that's 

Switch keyboard layout
-  After switching to qwerty: that?s

Log entry in either case:
2016-03-10 22:25:56,293 Translation(('THATS',) : that's)

## Version

I first noticed the issue after updating plover from the master branch 3151c85 and pulled ec93718 to check if it was fixed before creating this issue. The problem itself might be older because I used a fork for quite a while, though.

I am currently running a fairly up to date version of windows 10.

Edit: Also, capslock seems to affect Plover's output. I usually don't notice because I redirect capslock to ctrl but it probably shouldn't be the case.

**Comment by morinted** [comment]
Both of these are more or less expected behavior with how the code is written, but you are right that we could probably response to changes in the user's layout (especially for users that use multiple layouts at once, though I'm not sure if we can respond to that reliably).

- For the non-adapting keyboard layout, I could work around that by verifying the keyboard layout before sending each word, and updating Plover if the keyboard layout changes. I'll prepare a build on Saturday and get back to you to try it out.
- For the CAPS behavior, this is expected, because Plover emulates a keyboard, and keyboards respond to CAPS lock. Users can also use {#Caps_Lock} to control the caps key. It works this way on OS X as well.
