### ISSUE TITLE
Add menus to make Plover features more discoverable

### ISSUE THREAD

**Issue by timthelion** [openstenoproject/plover#425]
- App Menu (OS X) or File menu (Win/Linux):
    - About Plover (was: About… button on main window)
    - -- (separator)
    - Preferences… (was: Configure… button on main window)
- Edit
    - Add Translation to Dictionary…
    - Manage Dictionaries… (was: Dictionaries tab of Configuration window)
- Tools
    - Stroke Suggestions
    - Stroke Display
    - Dictionary Editor

- [ ] Remove About… button from main window
- [ ] Remove Configure… button from main window

- [ ] Remove the Dictionary tab from preferences.
    - Preferences tabs would then be: Machine | Logging | Display (on start ups + transparency) | Output

---

*Original request follows so that the conversation thread makes sense. :)*

Classification: Usability

Reproducibility: N/A

## Summary

I think that it would be better to have the stroke display and stroke suggestions butttons on the main screen, and perhaps to even get rid of the "display" tab in the configure dialog entirely. I consider the "stroke display" and "stroke suggetsions" to be "tools" and I expect those tools to present themselves. I don't expect to go searching for tools in the settings. What do you think?

**Comment by morinted** [comment]
I wouldn't put `stroke display` on the main dialogue for sure, because it's more for traditional steno users. It's not something that we really want to encourage new learners to pay attention to...

Now as for the suggestions window... that could happen. I can think of a couple pros/cons:

| Pros |
| ------ |
| Easy to get to for new learners, and intermediate stenographers. |
| Better for the use case of turning it on and off, because right now it is pretty hard to get to. |

| Cons |
| ------ |
| Less minimal main interface. Lots of people want Plover's main window to be tiny. |
| Not useful for experienced stenographers and will take up space. |
| We'll still have the display tab, so now there are two buttons for the same thing. |

Maybe we can meet halfway and introduce a command to raise the suggestions window. `PLOVER:SUGGESTIONS`. Then add it to the default dictionary with a sensible stroke.

**Comment by timthelion** [comment]
I guess the reason why you want a minimalistic main window is because you want to turn steno on and off easilly when transforming a normal querty keyboard to a steno one? In that case, have you considered implementing an input method for steno, like (pinyin). I know that doing input methods is difficult because there are like 3 different APIs for it on linux + apis on windows and Mac, but it's the right way™.

**Comment by morinted** [comment]
I think the reason people want it minimal is that it acts as a status window.

One can glance and see whether Plover's output is enabled or disabled, and what machine it is set to, and if that machine is connected.

I personally wouldn't mind another button but I've asked a couple users and of course no one really wants change. I think that by giving people a stroke, it's more in steno's nature. We only need a stroke to raise the window because Alt-F4 or e

**Comment by timthelion** [comment]
Right now, there are two buttons on the main window: `Configure` and `About`. What if there was `Configure` and `Help`. And pressing `Help` would load up a much larger help window with the stroke suggetions, an about box, and maybe a web widget with some plover tutorial open. And there could be a button in the stroke suggestions part of the window, for putting the stroke suggestions in their own window.

**Comment by stenoknight** [comment]
That sounds like a really bad idea to me. When I see a "Help" button, I
think "help using this particular piece of software", not "help with
learning the theoretical system that the software is an engine for".

On Tue, Mar 15, 2016 at 1:47 PM, Timothy Hobbs <notifications@github.com>
wrote:

> Right now, there are two buttons on the main window: Configure and About.
> What if there was Configure and Help. And pressing Help would load up a
> much larger help window with the stroke suggetions, an about box, and maybe
> a web widget with some plover tutorial open. And there could be a button in
> the stroke suggestions part of the window, for putting the stroke
> suggestions in their own window.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/openstenoproject/plover/issues/425#issuecomment-196944784>
>



-- 
Mirabai Knight, CRC, RDR
StenoKnight CART Services
917 576 4989
mkk@stenoknight.com
http://stenoknight.com

**Comment by timthelion** [comment]
Well, the button could be named something other than "Help". My point was more, "if this window has to remain small then why does it have an 'About! button on it. The 'About' button is pressed very rarely."

**Comment by balshetzer** [comment]
Brainstorming here:

What if the main window had a compact mode and a full mode. The compact
mode would be like today's status display with a "more" button or ">>", or
something similar. When pressed it would morph to the full mode where size
is not a concern. The exact details of what's in full mode would evolve but
it can be a fully featured UI rather than a tiny status display.

**Comment by stenoknight** [comment]
Oooh! That I could definitely see working! Nice idea, Hesky!

**Comment by benoit-pierre** [comment]
I think we should just add a menu, only keep the output / status / reconnect elements in the main frame.

**Comment by benoit-pierre** [comment]
To elaborate a little more: the dictionary editor, add translation and lookup dialogs, buttons to open the suggestions and paper tape, all those elements don't belong in the configuration dialog. It makes no sense to have to open the configuration dialog to access those functions.

Furthermore, all the other elements of the configuration dialog act on a temporary copy of the current engine configuration, and the changes are only applied when clicking "Save". Clicking "Cancel" does not save those changes, and the current engine configuration is left unmodified. But if you use the dictionary editor or the add translation dialog, then you're modifying the current engine configuration, and the changes are saved directly (unlike with the serial config or the keymap config dialogs). So if you add a new dictionary, and use the add translation dialog (without saving first and re-launching the configuration dialog), then you're not adding to your new dictionary...

**Comment by jeremy-w** [comment]
Coming from OS X, I'd suggest a menu structure something like:

- App Menu (Plover):
    - About Plover
    - -- (separator)
    - Preferences…
- Edit
    - Add Translation to Dictionary…
- Tools
    - Stroke Suggestions
    - Dictionary Editor
    - Stroke Display

Funny enough for those preferring a minimal Plover window, following platform conventions on OS X would lead to shifting both the About and Configure buttons out of the main window.

**Comment by morinted** [comment]
If we did the above, on other platforms could we use a simple menu instead of the current buttons?

```
File | Edit | Tools
--------------------
Output:
[x] Enable [ ] Disable
(X) Machine status: connected
```

File: About Plover | Preferences
Edit: Add Translation to Dictionary | Manage Dictionaries…
Tools: Stoke Suggestions | Stroke Display | Dictionary Editor

We could then remove the dictionary tab from preferences, and the dictionary management would be its own window. Preferences would be:  Machine | Logging | Display (on start ups + transparency) | Output

**Comment by jeremy-w** [comment]
I'd expect we could. I think on second thought it might make more sense to put the "Add Translation" and "Manage Dictionaries" menu items under "File" rather than "Edit".

This would also provide a natural way to expose some dialogs that are currently only accessible if you define a stroke for them, like the dictionary lookup tool.

**Comment by morinted** [comment]
I believe that the new user interface greatly meets or exceeds the changes you were thinking of, @timthelion 

I welcome further input in #571
