### ISSUE TITLE
Cache dictionary in sqlite (or similar)

### ISSUE THREAD

**Issue by tthurman** [openstenoproject/plover#456]
Classification: Performance
Reproducibility: Always

## Summary

Dictionary loading is slow, both during startup and when the dictionary editor opens. 

I suggest that
1) we should add a dictionary loader for sqlite files, along with json and rtf
2) when a json or rtf file is loaded, and there isn't a corresponding newer sqlite file, we automatically write one out
3) lookups in sqlite dictionaries should be handled by the sqlite libraries, not from having the whole dictionary loaded into memory by Plover

I could implement this at some point, if people think it's worthwhile.

**Comment by benoit-pierre** [comment]
That's 2 different problems.

The slow startup is due to the 'linting' done after loading the dictionary: canonizing the strokes. I think this linting could either be deactivated completely on load (with a function to check a dictionary for possible errors exposed somewhere else in the interface), or a timestamp could be stored, to only do this part when the dictionary has been changed.

The dictionary editor does not load the dictionaries again, and is only really slow on Linux. Blame wx and the way the grid/table work...

**Comment by tthurman** [comment]
Fair enough! I wonder whether we could populate, say, the first hundred rows, and do the rest if they scrolled downwards. I don't suppose people often load the editor in order to read the entire dictionary.

I'll close this issue. Thanks for your help.
