### ISSUE TITLE
Retrospective Delete Space fails to delete space after stroking "foo enable"

### ISSUE THREAD

**Issue by david-pitty** [openstenoproject/plover#472]
Classification: Bug

Reproducibility: Always

## Summary

Cannot use Retrospective delete space on word enable.

## Steps to Reproduce

1. I type: foo enable (stroked: TPAO/EPB/ABL)
2. use Retrospective delete space

## Expected Results

3.  fooenable

## Actual Results

3. foo enable (no change).

## Version

Plover v2.5.8+567.g52ebe0b.

Installed via: download from https://github.com/openstenoproject/plover/releases/tag/weekly-v2.5.8%2B567.g52ebe0b

## Notes
The example may not seem like a valid use case, but it's needed when "enable" is the first word on a new line and the before output space placement is used.

Workaround: use TK-LS to suppress the space before typing enable.

## Configuration

OS:
Windows 8.1

**Comment by benoit-pierre** [comment]
So it does not work because the retrospective command operate on the last 2 translations, so:

* `TEST/EPB/-BL` followed by retrospective delete space => ` testenable`; because "enable" is one translation (`EPB/-BL`)

* but `TEST/EPB/ABL` follow by retrospective delete space => ` test enable`; because the last two translations are "{en^}" (`EPB`) and "able" (`ABL`), with already no space between them

**Comment by david-pitty** [comment]
I see what you mean, this can be closed since its not a bug and I don't think there is much value added in implementing a retro delete that would handle prefixes. Thanks.
