### ISSUE TITLE
Russian layout

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#492]
Classification: Feature
## Summary

I've been talking with Sidorenko from Russia about the Russian steno layout.

```
// Layout:
С П Т В  *  К Т П И А
С К Н Р  *  С Н Р Е О
     И А   Е О
// Steno order
СПКТНВРИА*ЕОКСТНПРИЕАО

// Alternative layout for the Tréal:
#1 2 3 4 5 6 7 8 9 0
Х Ф Т В М Ё С Т В М Й
Ц С П К Р * Р Л К Н Ъ
      Н Е О А И

// Steno order for the Tréal:
ХЦФСТПВКМРНЕЁ*ОАИСРТЛВКМНЙЪ
```

See the PDF for the mapping of orthography:
[Russian alphabet and layout.pdf](https://github.com/openstenoproject/plover/files/247728/Russian.alphabet.and.layout.pdf)

> uppercase letters are for the left part of steno, lowercase - for the right part.

**Comment by morinted** [comment]
Here's an RTF export from Eclipse for some briefs:

[Russian_roots.txt](https://github.com/openstenoproject/plover/files/258104/Russian_roots.txt)

Note this is Cyrillic ANSI, so you'll need to open with encoding Windows 1251. I exported to UTF-8:

[Russian_roots_UTF.txt](https://github.com/openstenoproject/plover/files/258122/Russian_roots_UTF.txt)

**Comment by gordon-quad** [comment]
Any progress on that?

As far as I understood roots from second comment are for second Tréal layout so it is not suitable for Ireland steno layout?
So in order to use first layout I need to came up with my own dictionary from scratch?

I would gladly participate in this activity but unfortunately steno wasn't very popular in our country and the only book about stenotype theory that came out in Russia was written in 1951 and it is impossible to find it anywhere. The only thing I know is that it is based on Melani theory which was used initially for Itallian. Maybe your contact own this book or at least somebody from your team can point where to start with this Melani method?

**Comment by morinted** [comment]
I don't yet have access to a dictionary with the classic Ireland layout and the Russian theory, but once I do I will be able to develop a plugin for it.

I'd also like to share the theory book that was written for the Treal machine for realtime Russian.

[Учебник по машинной стенографии (американская клавиатура) Russian Theory - ARA.doc.zip](https://github.com/openstenoproject/plover/files/1533593/Russian.Theory.-.ARA.doc.zip)

**Comment by morinted** [comment]
Initial implementation of the Russian layout has been published as a plugin with dictionaries baked in. Named "Trillo", after its late creator.

**Comment by morinted** [comment]
Closing for now. If someone really wants the "classic" Russian layout to be implemented, please reopen this issue.

**Comment by ArtAdictedArchitect** [comment]
I’m going to start a slow burning long term project of getting Russian to work with Plover on a georgi or similar style board.

**Comment by Zireael07** [comment]
@ArtAdictedArchitect Are you talking about "classic" (Melani) Russian or Trillo's Russian?
