### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#588]
Classification: Documentation
## Summary

Update the Plover README -- it needs some TLC. I'd like to change from srt to md, and I'd like to add more marketting-speak along with graphics and pointers to contributing.md and OS-specific environment setup.

**Comment by morinted** [comment]
# Plover

Plover is a desktop application (written in Python) that allows anyone to use stenography to write on their computer.

Plover is part of the [Open Steno Project](http://opensteno.org). The Open Steno Project aims to provide everything you need to learn machine shorthand on your own, from free software, to cheap hardware, to learning resources. Skilled stenographers can also use Plover with their own dictionaries.

Head on over to [Plover's homepage](http://opensteno.org/Plover) or the [wiki](https://github.com/openstenoproject/plover/wiki) to get started.

## Installation

View the [installation guide](https://github.com/openstenoproject/plover/wiki/Installation-Guide) which covers downloading, installation, and initial configuration of Plover.

## Getting help

Having trouble with Plover?

The Wiki has several pages to help you:

- [Installation Guide](https://github.com/openstenoproject/plover/wiki/Installation-Guide)
- [Get Started with Plover](https://github.com/openstenoproject/plover/wiki/Beginner's-Guide:-Get-Started-with-Plover)
- [Supported Hardware](https://github.com/openstenoproject/plover/wiki/Supported-Hardware)
- [Troubleshooting Common Issues](https://github.com/openstenoproject/plover/wiki/Troubleshooting:-Common-Issues)

If the pages above don't solve your issue, consider asking the community. We are active on the [Plover Discord](https://discord.gg/0lQde43a6dGmAMp2) (a live chatroom service) and the [Ploversteno Google Group](https://groups.google.com/forum/#!forum/ploversteno) which is a more traditional mailing list.

If you think you've found a bug or would like to request a new feature, please [create an issue in this repository](https://github.com/openstenoproject/plover/issues/new) (be sure to fill out the form as best you can so that we can help you quickly!)

## Getting involved

The Open Steno Project is always growing, and could use your help! There are many challenges being faced.

### Coding

Currently, our [backlog of issues](https://github.com/openstenoproject/plover/issues) includes bugs and feature requests that Python developers can tackle. If you are unsure about whether you should work on an issue, just leave a note that you'd like to work on it and someone can speak up if there's a reason you shouldn't. See more in [CONTRIBUTING.md](https://github.com/openstenoproject/plover/blob/master/CONTRIBUTING.md)

If Python isn't your thing, there are other repos that would benefit from some tender love and care, including [StenoTray](https://github.com/SmackleFunky/StenoTray) (Java) and [StenoJig](https://github.com/JoshuaGrams/steno-jig) (JavaScript).

### Writing

Our Wiki is naturally rather broad as we try to discuss Plover's features as well as what stenography is over all. Edits to the Wiki and new page ideas are welcome. Do drop in to the Discord server to discuss before making large changes or changing the sidebar.

### Art

If you are a graphic artist, stenography is always in need of more art. The app's icons are worked on at [morinted/plover_icons](https://github.com/morinted/plover_icons) and contributions are welcome.

Plover's mascot, [Dolores](http://plover.stenoknight.com/2010/10/new-logo.html) is a little aged and could be reworked by anyone feeling brave enough to do so!

### UX and Web Design

Contributions in the form of UX improvement suggestions are welcome, it would help if suggestions are supported by studies. Remember that Plover is cross-platform, running on Windows, Mac, and Linux. This adds some additional challenges (for example, it is not easy to follow macOS's guidelines because it would be incompatible with the other operating systems).

For web designers, the code for the [Open Steno Project homepage](http://opensteno.org) can be found at our [openstenoproject.GitHub.io repo](https://github.com/openstenoproject/plover/tree/gh-pages). [Plover's homepage](http://opensteno.org/Plover) code is in this repo in the [gh-pages branch](https://github.com/openstenoproject/plover/tree/gh-pages). Both websites could use some love and passionate designers can discuss ideas on the Discord server. 

## Building in Development

Plover is cross-platform and has build instructions for each platform.

Please follow through for your system:

- [Windows](https://github.com/openstenoproject/plover/tree/master/windows)
- [macOS](https://github.com/openstenoproject/plover/tree/master/osx)
- [Linux](https://github.com/openstenoproject/plover/tree/master/linux)

----

## Open source licensing info

Plover is GPLv2+ as of version 3.1.0. See [LICENSE.txt](https://github.com/openstenoproject/plover/blob/master/LICENSE.txt) for details.

**Comment by cherryleaf** [comment]
## What is Plover?

Plover is a desktop application (written in Python) that allows anyone to use stenography to write on their computer.

Plover is part of the Open Steno Project. The Open Steno Project aims to provide everything you need to learn machine shorthand on your own, from free software, to cheap hardware, to learning resources. Skilled stenographers can also use Plover with their own dictionaries.

See Plover's homepage or the wiki to get started.

### Is it stable?

Plover is stable, but it is not mature software. 

>Note: Your normal keyboard shortcuts may not work

Once running, it will interpret all keystrokes according to the stenography dictionary you provide. When using the Sidewinder or any other normal keyboard with Plover, your normal keyboard shortcuts may not work. Use the mouse or stop the Plover program if you are unsure of what will result from typing.

## Installation

View the installation guide which covers downloading, installation, and initial configuration of Plover. Plover is cross-platform and has build instructions for each platform:

Windows
macOS
Linux

### Hardware requirements

See: 

### Supported stenotype protocols

QWERTY keyboards with n-key rollover (e.g. Microsoft SideWinder X4)
Gemini PR (a.k.a. Gemini Enhanced)
TX Bolt (a.k.a. Gemini TX)
Stentura
Treal
Passport

More information:

### Software requirements

xxxx
More information:

### Getting help and Troubleshooting

Having trouble with Plover?

The Wiki has several pages to help you:

Installation Guide
Get Started with Plover
Supported Hardware
Troubleshooting Common Issues

If the pages above don't solve your issue, consider asking the community. We are active on the Plover Discord (a live chatroom service) and the Ploversteno Google Group which is a more traditional mailing list.

If you think you've found a bug or would like to request a new feature, please create an issue in this repository (be sure to fill out the form as best you can so that we can help you quickly!)

## Contributing to the project

The Open Steno Project is always growing, and could use your help! There are many challenges being faced.

### Coding

Currently, our backlog of issues includes bugs and feature requests that Python developers can tackle. If you are unsure about whether you should work on an issue, just leave a note that you'd like to work on it and someone can speak up if there's a reason you shouldn't. See more in CONTRIBUTING.md

If Python isn't your thing, there are other repos that would benefit from some tender love and care, including StenoTray (Java) and StenoJig (JavaScript).

### UX and Web Design

We welcome UX improvement suggestions. It would help if suggestions are supported by research or other evidence. Plover is cross-platform, running on Windows, Mac, and Linux. This adds some additional challenges (for example, it is not easy to follow macOS's guidelines because it would be incompatible with the other operating systems).

For web designers, the code for the Open Steno Project homepage can be found at our openstenoproject.GitHub.io repo.
 
Plover's homepage code is in this repo in the gh-pages branch. Both websites could use some love and passionate designers can discuss ideas on the Discord server.

### Art

If you are a graphic artist, stenography is always in need of more art. The app's icons are worked on at morinted/plover_icons and contributions are welcome.

Plover's mascot, Dolores is a little aged and could be reworked by anyone feeling brave enough to do 

### Legal

Plover is GPLv2+ as of version 3.1.0. See LICENSE.txt for details.

**Comment by gdwaynewarner** [comment]
I would change two things:

(1) "macOS" should be "Mac OS"

(2) "rhymes with  'hover'" should be "rhymes with 'lover'"

That last one is because apparently "hover" is pronounced differently in the UK.

**Comment by morinted** [comment]
Thanks to you both, I'll take your changes into consideration when I revisit this.
