### ISSUE TITLE
Serial Port?

### ISSUE THREAD

**Issue by SlamGrier** [openstenoproject/plover#684]
HI, I'm downloading for the first time.  I have a Stentura Wave and Windows 8. . I cannot get Plover to recognize my serial port.  It says:

"WARNING: Can't open serial port. SerialException: could not open port": WindowsError(3 'The system cannot find the path specified.')

I have closed everything, restarted everything, unplugged and replugged in my cable. The cable itself is a USB bought from Stenograph.  

Would really like to try this so any hep would be appreciated.

**Comment by morinted** [comment]
- the COM port should appear in Device Manager when plugging/unplugging
your device. If it doesn't, you might need additional drivers for your
adapter.
- once you have the COM port, configure Plover. In the machine configure,
there is an option to scan for ports. Scan, then select the COM port for
your machine.
- save the config and your machine should be connected.
- you can open the paper tape to help debug.
- protocol should be Stentura.

On Feb 7, 2017 3:44 PM, "SlamGrier" <notifications@github.com> wrote:

HI, I'm downloading for the first time. I have a Stentura Wave and Windows
8. . I cannot get Plover to recognize my serial port. It says:

"WARNING: Can't open serial port. SerialException: could not open port":
WindowsError(3 'The system cannot find the path specified.')

I have closed everything, restarted everything, unplugged and replugged in
my cable. The cable itself is a USB bought from Stenograph.

Would really like to try this so any hep would be appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openstenoproject/plover/issues/684>, or mute the thread

**Comment by SlamGrier** [comment]
Thanks.  I have Windows 8 and I tried to download drivers from stenograph and they couldn't even be downloaded.  Here's the message I got.
![pic1](https://cloud.githubusercontent.com/assets/25621213/22715966/85974f02-ed61-11e6-994c-37dcaae9fccc.png)

**Comment by morinted** [comment]
Yep, you'll need the driver installed before continuing.

I had luck with the link on this page:
http://www.stenographsolutions.com/solution/index.php?View=files&CategoryID=3

**Comment by SlamGrier** [comment]
I've been unable to get this to work and I just realized something.  I only have USB.  Does this work with USB?

**Comment by morinted** [comment]
No. USB Stenograph is still in development.

Make sure you have the Stenographers drivers installed (meaning it doesn't
show up as an unknown device in Device Manager).

Then try a development version of Plover which should work with Stenograph
machines over USB:
https://ci.appveyor.com/project/morinted/plover/build/333-iinxxncf/job/6adfod77q7oq0ral/artifacts

**Comment by SlamGrier** [comment]
okay, that did it, I'm actually writing from my steno machine right now. Thanks for your help. Lot to learn.

**Comment by morinted** [comment]
Great to hear. Hopefully Plover 4 will support your machine natively.

**Comment by szeptarsmatthew** [comment]
quick question.  I have a student cybra, downloaded and got the drivers and
loaded up the developmental version of plover you suggested above.  Plover
shows the machine is connected, but I'm not getting any kind of output.  Am
I missing something in settings potentially?

**Comment by morinted** [comment]
The Cybra is older and uses a slightly different protocol, and at the moment is unsupported. It will only work over serial.

**Comment by szeptarsmatthew** [comment]
OK, thanks.  I was hoping your advice to the other person would work with
mine as well.  Just for your purposes, it did show as connected over USB, I
just couldn't get any kind of output on it.

**Comment by morinted** [comment]
Yes, it is being worked on. I've emailed Stenograph to see if they could
help.

**Comment by szeptarsmatthew** [comment]
that's so awesome.  Thanks for all the work you're doing on this project.

**Comment by tylerweitzman** [comment]
I am on a Stentura 400 SRT, latest Apr 1 pre-release Plover 4.0.0.dev8+8.ge062cda, 
 and Mac OS X 10.13.5 and I can't get it working.

At first, the port scan found nothing until I installed a new kext driver, then it found /dev/cu.usbserial, but when I try connecting with Plover I get a push notification saying
 "Warning Can't open serial port"
![image](https://user-images.githubusercontent.com/2078974/42117192-2719570c-7bb0-11e8-9f26-1b27e3252503.png)

Maybe it is not a Plover issue? How do I debug this?
This is my ubs-serial showing on Mac's equivalent of device manager
![image](https://user-images.githubusercontent.com/2078974/42117233-5891e3ee-7bb0-11e8-93d6-81b47b5f02af.png)

And this is what I get on Terminal when I run `screen /dev/cu.usbserial 9600`
```
ATV1S0=1&D0
fxf�����`���xxxxxx��x�x�x����x�x�x�=E�U�        ATV1S0=1&D0
fxf�����`���xxxxxx��x�x�x����x�x�x�=E�U�        ATV1S0=1&D0
fxf�����`���xxxxxx��x�x�x����x�x�x
```

I then try pressing keys on the Steno machine and do not see anything more show on screen.
