### ISSUE TITLE
bootstrap.sh is too distro-specific on Linux

### ISSUE THREAD

**Issue by tthurman** [openstenoproject/plover#715]
Classification: Enhancement

Reproducibility: n/a

## Summary

When bootstrap.sh detects it's running on Linux, it attempts to detect the distro. It has support for Arch and Ubuntu; if you're not running either of those, it halts. This is really unhelpful for everyone else!

The script needs to know the distro in order to install the dependencies. But if the distro is unknown, it only needs to warn the user that dependencies will not be installed automatically, and carry on from there. 

## Version

Current master HEAD

**Comment by benoit-pierre** [comment]
Yes, `bootstrap.sh` only supports Arch Linux and Ubuntu, as mentioned in the documentation. We don't want to keep on going with installing dependencies with pip if the distribution is not supported because:
- some things need to be installed with the distribution package manager anyway (e.g. Python, or `libusb` for `hidapi`)
- distribution's packages are preferred over pip's installs (especially for things like PyQt5)
- not all dependencies will be installed if we do that: PyQt5 is not required by Plover because the necessary Python distribution metadata is not provided by distributions packages

**Comment by benoit-pierre** [comment]
Closing: `bootstrap.sh` is no more... The Linux instructions have been changed to use pip for pretty much everything.
