### ISSUE TITLE
Glue Strokes (&) not gluing when in "Spaces After" mode

### ISSUE THREAD

**Issue by mighele** [openstenoproject/plover#719]
Classification: Bug

Reproducibility: Always

## Summary

When Plover is running with "Space placement: After output", glue strokes don't reliably glue together. Usually they will glue together 3 times and then not glue together (there will be a space in between items)

## Steps to Reproduce

1) My dictionary contains: "P*": "{&P}"
2) Set Plover to "Space placement: After output" in Output tab.
3) I press P* and release: letter "P" is output
Repeat step 3. Often it will correctly glue 3 P together but then will not glue correctly.
For example, after pressing P* 6 times your output will look like:
PPP P P P

## Expected Results

PPPPPP
(All Glue strokes are glued together with no spaces in between)

## Actual Results

PPP P P P
(Spaces in between some of the glue strokes)

## Version

Plover version 3.1.0.

Installed via: download from openstenoproject.org

## Notes

The glue functionality seems to work perfectly in "Spaces before output" mode. Maybe I'm one of a handful of users that prefer spaces after mode.

## Configuration

OS: Windows 10 Pro

**Comment by morinted** [comment]
Thanks for the detailed bug report.

Benoit Pierre has been reworking the formatter code in a branch: https://github.com/benoit-pierre/plover/tree/formatter_reformatted

You can grab a test build off of AppVeyor: https://ci.appveyor.com/project/benoit-pierre/plover/build/1066/job/x48siycounn864m1/artifacts

Note: since it's a major version bump, I recommend you back up your plover.cfg

**Comment by mighele** [comment]
That is a beautiful version of Plover! 👍 

Good work @benoit-pierre !

I've just checked and the glue strokes work fine on that version. Looking forward to it making it to the main branch!

**Comment by benoit-pierre** [comment]
Already fixed on master.
