### ISSUE TITLE
Midi Keyboard support

### ISSUE THREAD

**Issue by GBriotti** [openstenoproject/plover#742]
Classification: Feature (New)

Reproducibility: Not Applicable 

## Summary

A midi keyboard could be a good solutione for steno.  I find no references to midi keyboard in documentation (Probably I miss something?). I would like to know if you plan to support this kind of keyboard in the future.

TIA

**Comment by morinted** [comment]
A MIDI keyboard doesn't have a layout that you could steno on, unless there's something I'm missing.

**Comment by GBriotti** [comment]
The italian Senate use a midi keyboard for steno... it is the evolution of Michela machine adopted since 1880.

https://it.wikipedia.org/wiki/Macchina_Michela

**Comment by morinted** [comment]
Okay, if we are to implement this I'd prefer a machine + system combo (a set goal). Do you plan to write with the Italian theory? Do you have a document on how it works?

**Comment by GBriotti** [comment]
Well, I can ask for (probably it will in italian, I'll check or translate for english version).  Thank you for you interest.

**Comment by GBriotti** [comment]
Hi Ted, the picture is the key translation for Michela machine and the pdf explains the basics for the Michela steno system. Hope this helps.


[Michela in brief (ENG).pdf](https://github.com/openstenoproject/plover/files/906771/Michela.in.brief.ENG.pdf)
![keyboardmichela](https://cloud.githubusercontent.com/assets/27013654/24818268/ff4dcd74-1bdf-11e7-9e37-f11dbd35a3c1.jpg)

**Comment by morinted** [comment]
Do you know if the "real" machines they use for the senate use MIDI or do they use a different protocol?

**Comment by GBriotti** [comment]
Midi, with a simple midi->USB adapter.

**Comment by morinted** [comment]
This is a fantastic resource, thank you.

If I understand the document properly, this theory is phonetic (and not orthographic), and would need a dictionary to work. Are you able to find a dictionary anywhere? (Preferably in RTF, if it exists)

**Comment by GBriotti** [comment]
Yes. I have seen a Michela stenotypist able to catch a tongue twist in catalan without language knowledge... 

I think I can find a dictionary.

**Comment by tthurman** [comment]
This could also be adapted to use Stenotype theory. Something like this:

![stenotype suggestion](https://cloud.githubusercontent.com/assets/292241/24961791/da401fcc-1f91-11e7-9b55-cb9ca117c3b6.png)

MIDI keyboards are far more readily available than steno machines!

**Comment by Fubrite** [comment]
tthurman, the one thing that stands out for me with that layout, is how would you press the vertical keys together? E.g TK

**Comment by tthurman** [comment]
Good question: I don't know. Suggestions welcome!

I note that I accidentally switched P and T on the left; also that I forgot the number bar.

**Comment by tthurman** [comment]
I think someone who actually plays the piano would have better ideas than me :)

**Comment by keyb-cutter** [comment]
Perhaps you could eliminate the height difference between the white and the black keys pasting above the front part of the white keys a plastic thickness.

![keyboard midi stenotype](https://cloud.githubusercontent.com/assets/27416693/25025235/b45b3326-20a1-11e7-8506-69b3e8d08c85.jpg)

**Comment by keyb-cutter** [comment]
Well, I had an old broken keyboard in the cellar so I had a bit of fun studying the problem from a somewhat more practical point of view. 
For the thickness I used pvc foam panels glued to the keys (a lightweight material that does not weigh on the keys and is very easy to cut). Since I was there, I changed a bit the keys configuration to make it more appropriate. This can be done easily with standard size music keyboards by releasing the springs and dismounting and reassembling the keys in a different position on the chassis. I also reduced the width of the vocal keys to reduce a bit the total width of the keyboard (to further reduce the width of the keyboard with regards to the right hand, is also possible to reverse the position of the two last keys on the right so that the group T/S, D/Z could be closer and more accessible from the little finger). 
As you can see, this is only a study and not a precision work. The pvc thicknesses should be shaped accurately and preferably black keys with a squared profile should be used to minimize the space between the lower and upper keys. 
Moreover, there is still the issue of the number bar. Perhaps, since now all MIDI keyboards (even the cheaper ones) are now touch sensitive (velocity/aftertouch), could be possible to use this features to differentiate numbers writing...

![stenotype midi with layout](https://cloud.githubusercontent.com/assets/27416693/25309513/c635084e-27cf-11e7-8273-a3209140d588.jpg)

![keys](https://cloud.githubusercontent.com/assets/27416693/25309521/20ab90f4-27d0-11e7-932e-a05cdbe12f60.jpg)

![chassis](https://cloud.githubusercontent.com/assets/27416693/25309525/45fb6cc6-27d0-11e7-94aa-2dda23ba2f52.jpg)

![chassis 2](https://cloud.githubusercontent.com/assets/27416693/25309570/0f1e5140-27d1-11e7-8ffa-fe8c2e2ec4c3.jpg)


![tastiera 2](https://cloud.githubusercontent.com/assets/27416693/25309540/6e1891ac-27d0-11e7-99f8-44b9214f2e89.jpg)

**Comment by MartyGentillon** [comment]
Alternately, with a grid controller (such as a [linnstrument](http://www.rogerlinndesign.com/linnstrument.html)), it could be laid out very much like a normal steno machine.

**Comment by benoit-pierre** [comment]
https://pypi.org/project/plover-midi/
