### ISSUE TITLE
Eliminate suffix folding

### ISSUE THREAD

**Issue by Jorge-plo** [openstenoproject/plover#861]
## Summary

I'm using Plover in Spanish, and I'd like to eliminate the suffix folding, because they are useful for English ortographic rules, but not for Spanish.

**Comment by morinted** [comment]
This could be done with a Spanish-layout plugin. I would need more information on how you are using Plover in Spanish to help.

**Comment by morinted** [comment]
For now I'm going to close this due to inactivity, but I can say that it is very possible to eliminate suffix folding, as well as English orthography rules. It is done through a "system" plugin, which will be documented and anyone can implement after 4.0.0 is released. For now, if you have specifications on how to implement your theory, the Plover developers can assist. Just view all the issues related to the "systems" label for more info. Cheers!
