### ISSUE TITLE
Plover not properly detecting keystrokes

### ISSUE THREAD

**Issue by lukeoftheaura** [openstenoproject/plover#905]
## Summary

Plover isn't properly detecting keystrokes, I think this is that it's not detecting when the key is released. When it is enabled any keys I press are swallowed by the program and not output but then at some point (seemingly randomly) it will register all the keys I previously pressed and output something like  STKPWHRO*EPBLGT.

## Reproducing

Try just using plover with a keyboard.

## Plover Version

Plover 4.0.0.dev6+5.ga564116

## System

* Linux
* Distro: Antergos linux x64
* DE: None
* WM: `i3-gaps`
* Plover is running from appimage

**Comment by morinted** [comment]
Plover 3.1 was reported working on this system before Plover 4 was run.

**Comment by benoit-pierre** [comment]
3.1.0 or 3.1.1?

**Comment by lukeoftheaura** [comment]
3.1.1

**Comment by benoit-pierre** [comment]
OK. No changes in the keyboard emulation handling between 3.1.1 and 4.0.

How was 3.1.1 installed?

Can you run from source, or maybe install from [AUR](https://aur.archlinux.org/packages/plover-git/) (since you're using Antergos), and see if the behavior is the same? Additionally, could you check the behavior when running `stty -echo; python -m plover.oslayer.keyboardcontrol; stty echo` (try a few strokes, see if you can reproduce the issue) from the source directory?

**Comment by lukeoftheaura** [comment]
3.1.1 was from the `plover` AUR package, I'll try installing 4.0 from AUR.

**Comment by lukeoftheaura** [comment]
I can't seem to install 4.0 from AUR from `plover-git` due to weird conflicts in python. This is what happens when you have `pip` and `pacman` both trying to manage python libs -_-

**Comment by benoit-pierre** [comment]
What conflicts are those?

**Comment by lukeoftheaura** [comment]
issue closed, original problem was down to user error, AUR problem has been fixed
