### ISSUE TITLE
Data representation in the Stenograph Overview wiki page

### ISSUE THREAD

**Issue by NetherOrb** [openstenoproject/plover#937]
More of a criticism regarding the data for speed for various input devices in the wiki page Stenography Overview: 

The list of of speeds represented as the 'top speeds' for other input methods other than steno are not honest. Averages are shown for say qwerty or shorthand writing isnt shown at all, but then shows the top speeds for steno. And even some of the data for top qwerty or similar are simply untrue. This makes the data that is presented heavily biased and a turn off for those who are gauging whether or not to take time and effort into learning stenography.

Im all for the goal of spreading the word of stenography if it truly is a superior input device for computers; but let the data show whats true. I for one give a damn if its qwerty, dvorak, touch, or wine glasses, etc. 

I think the bigger goal is to see what the truly superior means of input is. Also, im not saying to include every input device under the sun but to at least have the same representation for each input device. I.e., steno average: x steno top: x, qwerty average: x qwerty  top: x, etc. (In general, more research into this topic would be useful)

**Comment by morinted** [comment]
I've taken a stab at normalizing the numbers a little bit, we can adjust further if you have more input.

https://github.com/openstenoproject/plover/wiki/Stenography-Overview#what-is-stenography

The problem with trying to find "average stenographer" is that there are very few average stenographers (because not everyone uses steno, as opposed to everyone using a keyboard). That's what the "amateur stenographer" stat is trying to get at. 160 WPM seems to be an achievable number for people, without taking the extra step to become professional, which is where the graduation speed of 225 WPM comes into play.
