### ISSUE TITLE
On install, error: "The code execution cannot proceed because VCRUNTIME140.dll was not found."

### ISSUE THREAD

**Issue by Greygal** [openstenoproject/plover#941]
## Summary

Just attempted to install latest weekly 4.0 build (plover-4.0.0.dev8.8.ge062cda-win32.setup.exe).  Installation appeared to go smoothly.  When I attempt to start Plover, I receive a pop-up error message stating, "The code execution cannot proceed because VCRUNTIME140.dll was not found.  Reinstalling the program may fix this problem."  Downloading and installing "vc_redist.x86.exe" from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads appears to have resolved the issue.
This was on Windows10, latest updates.

## Reproducing

Install Plover 4.0 using release listed above.
I had "start plover after install" box checked.
After installation is complete, when it attempts to start up plover automatically after install, received error message listed above.

## Plover Version

Plover 4.0.0.dev8+8.ge062cda

## System

Windows10

**Comment by DanLanglois** [comment]
Today's error is “VCRUNTIME140.dll is missing”. And then, you fixed it, with the Microsoft redistributable. However,  the Microsoft redistributable places stuff system-wide, which isn't supposed to be necessary here I think.  So what we have in this case is an unsatisifiable dependency error. 

I consider, then, how DLL problems have different faces. Sometimes when I'm doing a little project I'm not careful enough and accidently add a dependency for a DLL that I am not aware of. Note this, which benoit-pierre committed on Nov 13, 2017, 'windows: fix missing Visual C++ Redistributable DLL error':

plover/setup.py
181       # Fix Visual C++ Redistributable DLL location.
182       os.rename(os.path.join(dist_dir, 'data', 'vcruntime140.dll'),
183       os.path.join(dist_dir, 'vcruntime140.dll'))

So this is in setup.py, and what setup.py is for, is to describe all of the  metadata about your project.  Therefore,  I don't think this code is in the right place, because what it does, or attempts to do, is to include a run-time library ( a .dll file) that PyInstaller does not know about from any other source. 

I mention PyInstaller, and let's consider as well, what is the 'spec file'? The spec file tells PyInstaller how to process your script.  The spec file is actually executable Python code. PyInstaller builds the app by executing the contents of the spec file. My thinking, here, is that what we have is a case where maybe it could be useful to modify the spec file. 

I hope I'm not being irritatingly redundant, I'm repeating myself, but I'm just working this out making it up as I go. It's been a while since I've done any Python. Take it with a grain of salt. But I mean, because you want to include this run-time library (this .dll file) that PyInstaller does not know about from any other source, therefore, the way that it works, is the way to do this is, is you create a spec file. And after you have created a spec file and modified it as necessary, you build the application by passing the spec file to the pyinstaller command or such. 

For many uses of PyInstaller you do not need to examine or modify the spec file. It is usually enough to give all the needed information (such as hidden imports) as options to the pyinstaller command and let it run. But you see, when you create a spec file, most command options are encoded in the spec file. When you build from a spec file, those options cannot be changed. If they are given on the command line they are ignored and replaced by the options in the spec file. Again: after PyInstaller creates a spec file, or opens a spec file when one is given instead of a script, the pyinstaller command executes the spec file as code. Your bundled application is created by the execution of the spec file.

Moving on, the statements in a spec file create instances of four classes, Analysis, PYZ, EXE and COLLECT. And the following is an shortened example of a spec file for a minimal, one-folder app:

block_cipher = None
a = Analysis(['minimal.py'],
     pathex=['/Developer/PItests/minimal'],
     binaries=None,
     datas=None,
     hiddenimports=[],
     hookspath=None,
     runtime_hooks=None,
     excludes=None,
     cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
     cipher=block_cipher)
exe = EXE(pyz,... )
coll = COLLECT(...)

Note in particular, the part about binaries. These are non-python modules needed by the scripts, and so forth. I mean, I'm not sure it's clear that I'm talking about pyInstaller, the freezing tool. I haven't looked at this stuff (plover) in maybe years, or programmed python in years, I'm trying to recall if you are using pyInstaller or yes, there are alternatives. But still, the setup.py file is at the heart of a Python project. It's not the place for this. Let's return, then, to the issue of “VCRUNTIME140.dll is missing”. That, is I think a file that os extracted during installation, and should be in PATH during installation, but it appears something is going wrong on your system during installation, and that file isn't found. So it's like this, you ponder the contents of your environment's root folder, and you figure that this DLL should live in there, and where is it then? And then let's see that code again:

plover/setup.py
181       # Fix Visual C++ Redistributable DLL location.
182       os.rename(os.path.join(dist_dir, 'data', 'vcruntime140.dll'),
183       os.path.join(dist_dir, 'vcruntime140.dll'))

So the idea here is that adding this thing (''vcruntime140.dll') to PATH solves these issues.

Anyways, I have rambled. My conclusions are that these lines don't do anything, just delete them, lines 181, 182, 183. Whatever they do,  are try to do, it's a workaround on one person's dev comp. The issue here being with setup.py, it only happens on a dev box, and you will indeed need that dll, 'vcruntime140.dll', from somewhere. Maybe it gets distributed with python, supposedly. You recently upgraded the python version, these are exactly the sort of dependency issues that happen on dev boxes. It's a dev box issue, and not precisely a 'When I attempt to start Plover' issue. setup.py never even gets bundled into the actual distribution, right? If that makes sense..? ;)

**Comment by benoit-pierre** [comment]
We do not use PyInstaller (we used too). Our distribution is based on the official Windows x86 embeddable distribution from Python, of which `vcruntime140.dll` is part of.

`setuptools` does provide various commands to create distributions: source, binary (wheel/egg), but also Windows installer or RPM package. So the command is where it should be.y

Anyway, I think the problem is that `python.exe/pythonw.exe` live in a sub-directory of `plover.exe`, so the DLL is not in the path (that's why I moved it one directory up, beside the Plover executable). Maybe we should stop using a separate sub-directory for the Python embeddable distribution (this was only done to reduce clutter in the main directory).

**Comment by DanLanglois** [comment]
'Anyway, I think the problem is that python.exe/pythonw.exe live in a sub-directory of plover.exe, so the DLL is not in the path (that's why I moved it one directory up, beside the Plover executable). Maybe we should stop using a separate sub-directory for the Python embeddable distribution (this was only done to reduce clutter in the main directory).'

I understand most of this, but I have an issue. To start, here is what I do understand: You're saying that currently, plover provides a batch file or generated shortcut that directly calls the python.exe or pythonw.exe with the required command-line arguments. And, packages are currently  installed as directories alongside the Python executable to ensure they are available on the path. But also, currently,  packages cannot be located in other locations. There is currently no opportunity to specify the search path before launching the application. This is because Plover is not using a specialized executable as a launcher. Now, with a customized launcher, there would be no obvious indications that the program is running on Python. And in general, an application written in Python does not necessarily require users to be aware of that fact. But currently, things are not that transparent/do not appear that professional. And one more thing, there's a bug! Plover is acting like there is this third-party package, that *should* be installed by the application installer alongside the embedded distribution. Therefore,  I was speculating that this is a Plover 3.5 bug maybe, because it seemed like suddenly the embedded distribution was missing the Microsoft C Runtime. I mean, I speculated that it did, here: 

'it's supposed to come with Python. .. don't .. assume that VCRUNTIME140.dll (apparently) isn't shipped by Python to Windows. It is supposed to be, ..'

Again: 

'I still think the DLL is supposed to come with python, used to come with python, does come with python..'

And here is your reply:

'Our distribution is based on the official Windows x86 embeddable distribution from Python, of which vcruntime140.dll is a part of.'

Now, stop! This is the part that I don't understand. What is this so-called 'official Windows x86 embeddable distribution from Python'? I don't remember that, though it's been a while. I looked this up, and yes, got it, here is the issue. Actually, vcruntime140.dll is *not* a part of that new ZIP file containing a minimal Python environment. Not to digress, but I'm looking at the specifications, which say that the standard library is included as pre-compiled and optimized .pyc files in a ZIP, and python3.dll, python36.dll, python.exe and pythonw.exe are all provided. Specifically *not* included, for example, are Tcl/tk (including all dependants, such as Idle), pip and the Python documentation.

I'm emphasizing whether the embedded distribution does  include the Microsoft C Runtime?

Answer: no, apparently it doesn't! So yes, in a sense, it's a python bug sort of. Because now, it has become  the responsibility of the application installer to provide third-party packages. Also tricky, is that we may not tend to always notice this issue, because the runtime may have already been installed on a user’s system previously or automatically via Windows Update.  

It's actually 'notes on this release' for Python 3.5.1, that there are' redistributable zip files containing the Windows builds, making it easy to redistribute Python as part of another software package'.

Always, this was a subtle issue to figure out though, because who would have thought that Windows does not include a system supported installation of Python? Thus, actually, it's worth pausing to think that it's been CPython team all along, that has compiled Windows installers (MSI packages) with every release for many years.

**Comment by DanLanglois** [comment]
I also observe plover/.travis.yml and have a question. The is the idea of opening a separate issue about it perhaps, but I'm looking at this part:

14 install:
15  - ./ci/travis.sh setup
16  
17  script:
18  - ./ci/travis.sh build

Noting that okay, install is setup and script is build. Or how to explain: this 'travis.sh' file is an executable file. Obviously, of course, but I emphasize that I wonder what's up -- I wonder if the executable file is necessary here, if only because there is a bug. I mean, that I notice how the recent pull requests are failing the travis testing. I checked this when my own pull request failed these integration tests. I had only deleted three lines, the lines I've mentioned up the thread:

plover/setup.py
181 # Fix Visual C++ Redistributable DLL location.
182 os.rename(os.path.join(dist_dir, 'data', 'vcruntime140.dll'),
183 os.path.join(dist_dir, 'vcruntime140.dll'))

Deleting these lines doesn't, I think, actually do anything, because these lines don't actually do anything, right? So my hypothesis was that I'd find a bug in  plover/.travis.yml, which is how I wound up looking at travis.sh. And I find this: 

setup()
{
  setenv
  # Install system dependencies.
  builddeps=(
    # dbus-python:
    libdbus-1-dev
    libdbus-glib-1-dev
    # hidapi:
    libudev-dev
    libusb-1.0-0-dev
  )
  if is_deployment
  then
    builddeps+=(
      # AppImage:
      libfuse2
      # Python:
      libbz2-dev
      libgdbm-dev
      liblzma-dev
      libncurses5-dev
      libreadline-dev
      libsqlite3-dev
      libssl-dev
      zlib1g-dev
      # PyQt5:
      libasound2
      libegl1-mesa
      libfontconfig1
      libgl1-mesa-glx
      libnss3
      libxcomposite1
      libxcursor1
      libxi6
      libxrandr2
      libxss1
      libxtst6
    )
  fi
  run sudo apt-get install -qq "${builddeps[@]}"
  # Setup development environment.
  bootstrap_dev --user
}

Now, towards the end of that, note the part like this:

run sudo apt-get install -qq "${builddeps[@]}"

And this generates and executes a line like this:

sudo apt-get install -qq libdbus-1-dev libdbus-glib-1-dev libudev-dev libusb-1.0-0-dev

And the error that this generates looks like this:

sudo apt-get install -qq libdbus-1-dev libdbus-glib-1-dev libudev-dev libusb-1.0-0-dev
E: Package 'libdbus-glib-1-dev' has no installation candidate
E: Package 'libudev-dev' has no installation candidate
E: Unable to locate package libusb-1.0-0-dev
E: Couldn't find any package by glob 'libusb-1.0-0-dev'
E: Couldn't find any package by regex 'libusb-1.0-0-dev'
The command "./ci/travis.sh setup" failed and exited with 100 during .
Your build has been stopped.

Here: https://travis-ci.org/openstenoproject/plover/builds/384323394?utm_source=github_status&utm_medium=notification

What went wrong? Well, again, here's the line:

sudo apt-get install -qq libdbus-1-dev libdbus-glib-1-dev libudev-dev libusb-1.0-0-dev

At first, one might assume that something here doesn't actually exist. But actually, these are familiar stuff. Therefore, my first suggestion is not to bother with adding -qq No output except for errors. I wouldn't mind seeing the output. And then, I'm wondering about how the packaging system uses a private database to keep track of which packages are installed. Also, which packages are not installed, and which are available for installation. To update this list, we would use the command apt-get update, as here:  

- sudo apt-get update

So, before this:

14 install:
15  - ./ci/travis.sh setup
16  
17  script:
18  - ./ci/travis.sh build

There could, I think,  be added something like this:



And I will say, here, that I don't know why it can't go right into plover/.travis.yml like that. I mean, right into the 'YAML Ain't Markup Language' of '.travis.yml'. Indeed, I'd probably think of the 'install:' part in these terms:

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -qq libdbus-1-dev libdbus-glib-1-dev libudev-dev libusb-1.0-0-dev

I contrast this, this is just pseducode and may not run, with what is there now, which we know does not run and yet is as involved as this:

install:
 - ./ci/travis.sh setup

Which is, I guess, just an include file, where travis.sh shows, again, though it is long and I've pasted it once already, I'm belaboring the point that I think this could all be one line, so here it is again:

setup()
{
  setenv
  # Install system dependencies.
  builddeps=(
    # dbus-python:
    libdbus-1-dev
    libdbus-glib-1-dev
    # hidapi:
    libudev-dev
    libusb-1.0-0-dev
  )
  if is_deployment
  then
    builddeps+=(
      # AppImage:
      libfuse2
      # Python:
      libbz2-dev
      libgdbm-dev
      liblzma-dev
      libncurses5-dev
      libreadline-dev
      libsqlite3-dev
      libssl-dev
      zlib1g-dev
      # PyQt5:
      libasound2
      libegl1-mesa
      libfontconfig1
      libgl1-mesa-glx
      libnss3
      libxcomposite1
      libxcursor1
      libxi6
      libxrandr2
      libxss1
      libxtst6
    )
  fi
  run sudo apt-get install -qq "${builddeps[@]}"
  # Setup development environment.
  bootstrap_dev --user
}

I'm a newbie here, so when I say I don't know why we can't do it in one line, let me emphasize the part that I don't know.

**Comment by morinted** [comment]
CI is fixed in PR #952

**Comment by Greygal** [comment]
Thank you!
