### ISSUE TITLE
Plugin idea: Translation log paper tape

### ISSUE THREAD

**Issue by morinted** [openstenoproject/plover#978]
## Summary

As I've been demoing steno and running Twitch streams, there's one widget that I've wanted over and over to show how raw steno breaks down into words. Basically a paper tape, but each row is the resulting translation instead of each stroke. For example, where you'd have:

```
<<Paper Tape>>
HRETS
PWAOEU
AUFLT
TPURPB
TAOUR
TPH-T
KAT
HROG
SAUB
SEBGS
```

This new widget would look more like:

| Translation Log |  |
|----------------|--|
| HRETS | let's |
| PWAOEU | buy |
| AUFLT | all of the |
| TPURPB/TAOUR | furniture |
| TPH-T | in the |
| KAT/HROG | catalog |
| SAUB | {sub^} |
| SEBGS | section |
```

This would let people see how words are constructed better, as well as what maps to what in your dictionary, which would be especially useful when demonstrating speed.

I think it would also be cool if you could copy from that window, for output to raw steno like `AUFLT TPURPB/TAOUR TPH-T KAT/HROG` as well as an ASCII representation of the table.

**Comment by grenzionky** [comment]
doesnt the suggestions window already do this?

**Comment by gdwaynewarner** [comment]
I'm not in Ted's head, but chances are good he wants something that will stay on the screen. It has been quite a while since I used the Suggestions window, but if I recall correctly, you stroke an outline, the Suggestions window shows you the potential  translations, then you stroke another word, and the previous suggestions go away.

Not very helpful when trying to demonstrate how steno works when the examples disappear like that.

**Comment by greenwyrt** [comment]
[plover-tapey-tape](https://github.com/rabbitgrowth/plover-tapey-tape) has something similar
